'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,CheckCircle2,Cpu,HardDrive,MemoryStick,Microchip,PackageCheck,Rotate3D,Wrench,Zap} from 'lucide-react';
import * as THREE from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';

type Id='psu'|'motherboard'|'cpu'|'ram'|'ssd'|'gpu';
type Part={id:Id;name:string;icon:typeof Cpu;instruction:string;why:string;start:[number,number,number];target:[number,number,number]};
const PARTS:Part[]=[
{id:'psu',name:'Power Supply (PSU)',icon:Zap,instruction:'Slide the PSU into the rear power bay.',why:'The PSU converts wall power into safe low-voltage power.',start:[-5.3,1.25,-2.0],target:[3.55,1.18,-1.55]},
{id:'motherboard',name:'Motherboard',icon:Microchip,instruction:'Mount the motherboard onto the chassis standoffs.',why:'The motherboard connects every major PC component.',start:[-5.0,1.0,.15],target:[2.25,1.05,.35]},
{id:'cpu',name:'CPU / Processor',icon:Cpu,instruction:'Place the CPU into the square socket.',why:'The CPU executes the computer’s instructions.',start:[-5.6,.9,2.25],target:[1.65,1.35,.15]},
{id:'ram',name:'RAM Memory',icon:MemoryStick,instruction:'Push the RAM into the DIMM slot beside the CPU.',why:'RAM holds information the CPU needs quickly.',start:[-4.0,.95,2.25],target:[2.45,1.45,.05]},
{id:'ssd',name:'M.2 NVMe SSD',icon:HardDrive,instruction:'Install the M.2 SSD flat on the motherboard.',why:'The SSD stores the operating system, apps and files.',start:[-2.55,.9,2.25],target:[2.55,1.36,.9]},
{id:'gpu',name:'Graphics Card (GPU)',icon:PackageCheck,instruction:'Seat the graphics card in the PCIe slot.',why:'The GPU renders games, video and 3D graphics.',start:[-2.75,1.2,-2.0],target:[2.2,1.75,1.45]}
];
const mat=(c:number,m=.18,r=.42)=>new THREE.MeshStandardMaterial({color:c,metalness:m,roughness:r});
const box=(w:number,h:number,d:number,c:number,r=.04)=>new THREE.Mesh(new RoundedBoxGeometry(w,h,d,4,Math.min(r,w/4,h/4,d/4)),mat(c));
function add(g:THREE.Group,o:THREE.Object3D,x:number,y:number,z:number){o.position.set(x,y,z);g.add(o);return o}
function cyl(r:number,h:number,c:number){return new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,28),mat(c,.3,.35))}
function fan(g:THREE.Group,x:number,y:number,z:number,vertical=false){const ring=new THREE.Mesh(new THREE.TorusGeometry(.38,.055,10,30),mat(0x111518));ring.position.set(x,y,z);ring.rotation.x=vertical?0:Math.PI/2;g.add(ring);const hub=cyl(.09,.08,0x20272b);hub.position.set(x,y,z);if(!vertical)hub.rotation.x=Math.PI/2;g.add(hub)}
function makePart(id:Id){const g=new THREE.Group();
 if(id==='psu'){g.add(box(1.9,1.15,1.65,0x25292c,.08));fan(g,0,.59,0);add(g,box(.42,.2,.05,0x080a0b),-.45,.02,.84);add(g,box(.16,.2,.05,0x8a9295),.15,.02,.84)}
 if(id==='motherboard'){g.add(box(3.35,.14,2.8,0x174f3e,.03));add(g,box(.82,.08,.82,0xb9b8aa),-.55,.14,-.45);for(const x of [.2,.42,.64,.86])add(g,box(.075,.15,1.65,0x15191b,.01),x,.17,-.2);for(const z of [.5,.82,1.08])add(g,box(2.45,.08,.1,0xd4d6d2,.01),-.05,.16,z);add(g,box(.5,.35,.85,0x9ba2a3,.03),-1.43,.25,-.72);add(g,box(.62,.18,.62,0x31383b,.03),.85,.18,.72)}
 if(id==='cpu'){g.add(box(.76,.16,.76,0x314047,.035));add(g,box(.64,.07,.64,0xd1cfc5),0,.12,0)}
 if(id==='ram'){g.add(box(1.72,.62,.17,0x174837,.02));for(let x=-.62;x<=.62;x+=.31)add(g,box(.23,.3,.04,0x111719,.01),x,.03,.1);for(let x=-.72;x<=.72;x+=.12)add(g,box(.055,.08,.03,0xd7b552,.004),x,-.34,.04)}
 if(id==='ssd'){g.add(box(1.5,.12,.48,0x175b42,.02));for(let x=-.42;x<=.35;x+=.27)add(g,box(.2,.08,.3,0x101719,.01),x,.1,0);const s=cyl(.055,.03,0xd4b45b);s.position.set(.66,.09,0);g.add(s)}
 if(id==='gpu'){g.add(box(3.25,.82,1.28,0x242a2e,.09));fan(g,-.72,.43,0);fan(g,.72,.43,0);add(g,box(2.6,.06,.1,0xd5ad4e),0,-.45,.45);add(g,box(.12,1.05,1.42,0xa4abad),-1.67,0,0)}
 g.traverse(o=>{if((o as THREE.Mesh).isMesh){(o as THREE.Mesh).castShadow=true;(o as THREE.Mesh).receiveShadow=true}});return g}
function room(s:THREE.Scene){const table=box(15.5,.45,8.6,0x665446,.15);table.position.set(-.2,.28,0);s.add(table);const matTop=box(14.4,.04,7.45,0x151c20,.06);matTop.position.set(-.2,.53,0);s.add(matTop)}
function chassis(s:THREE.Scene){const g=new THREE.Group(),metal=0x30363a,edge=0x555d61;
 // OptiPlex-style tower laid on its service side: open face points upward.
 add(g,box(5.8,.18,5.0,metal,.04),2.5,.66,0); // motherboard tray
 add(g,box(5.8,4.0,.16,metal,.04),2.5,2.55,-2.42); // rear wall
 add(g,box(.18,4.0,5.0,0x24292c,.04),5.32,2.55,0); // front wall
 add(g,box(.18,4.0,5.0,0x24292c,.04),-.32,2.55,0); // back I/O wall
 for(const z of [-2.25,2.25])add(g,box(5.8,.14,.14,edge,.025),2.5,4.5,z);
 // drive cage + PSU bay + recognizable front intake
 add(g,box(1.45,1.65,1.85,0x3b4246,.04),4.35,1.55,.75);add(g,box(2.1,.7,1.85,0x202629,.04),3.7,.98,-1.48);
 for(const y of [1.45,2.45,3.45]){const f=cyl(.48,.08,0x151a1d);f.rotation.z=Math.PI/2;f.position.set(5.2,y,-.65);g.add(f)}
 // rear expansion slots and motherboard standoffs
 for(let z=-.6;z<=1.6;z+=.36)add(g,box(.1,.18,.27,0x111517,.01),-.2,1.6,z);
 for(const [x,z] of [[.75,-.8],[2.0,-.8],[3.25,-.8],[.75,.55],[2,.55],[3.25,.55]]){const st=cyl(.055,.12,0xc5a54d);st.position.set(x,.83,z);g.add(st)}
 // front fascia so silhouette reads as a desktop tower
 add(g,box(.12,3.45,4.25,0x171b1e,.05),5.42,2.55,0);for(let y=1.15;y<4;y+=.3)add(g,box(.03,.12,3.4,0x343b3f,.01),5.5,y,0);
 s.add(g)}
export default function AssemblyLab({onBack}:{onBack:()=>void}){const canvasRef=useRef<HTMLCanvasElement>(null),currentRef=useRef(0),installedRef=useRef<Id[]>([]);const[current,setCurrent]=useState(0),[installed,setInstalled]=useState<Id[]>([]),[session,setSession]=useState(0),[feedback,setFeedback]=useState('Rotate the real PC chassis, identify the glowing part, then install it in the highlighted location.');const active=PARTS[current],complete=installed.length===PARTS.length;
 useEffect(()=>{currentRef.current=current},[current]);useEffect(()=>{installedRef.current=installed},[installed]);
 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;canvas.style.touchAction='none';const scene=new THREE.Scene();scene.background=new THREE.Color(0x0a1014);scene.fog=new THREE.Fog(0x0a1014,24,44);const camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(13.2,10.8,15.5);const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.enableZoom=true;controls.enablePan=true;controls.minDistance=7;controls.maxDistance=28;controls.target.set(.15,1.6,0);scene.add(new THREE.HemisphereLight(0xe4f4ff,0x30251d,2.7));const key=new THREE.DirectionalLight(0xfff0dc,4.6);key.position.set(7,13,8);key.castShadow=true;scene.add(key);const fill=new THREE.DirectionalLight(0x71dce8,1.7);fill.position.set(-8,7,5);scene.add(fill);room(scene);chassis(scene);
 const groups=new Map<Id,THREE.Group>(),ghosts=new Map<Id,THREE.Mesh>();for(const p of PARTS){const g=makePart(p.id);g.position.set(...p.start);groups.set(p.id,g);scene.add(g);const ghost=new THREE.Mesh(new THREE.BoxGeometry(p.id==='motherboard'?3.35:p.id==='gpu'?3.25:p.id==='psu'?1.9:p.id==='ram'?1.72:p.id==='ssd'?1.5:.76,.12,p.id==='motherboard'?2.8:p.id==='gpu'?1.28:p.id==='psu'?1.65:p.id==='ram'?.17:p.id==='ssd'?.48:.76),new THREE.MeshBasicMaterial({color:0x61e1eb,wireframe:true,transparent:true,opacity:.7}));ghost.position.set(...p.target);ghosts.set(p.id,ghost);scene.add(ghost)}
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),point=new THREE.Vector3(),offset=new THREE.Vector3();let dragging:Id|null=null;const pointerAt=(e:PointerEvent)=>{const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1);ray.setFromCamera(pointer,camera)};const down=(e:PointerEvent)=>{if(installedRef.current.length===PARTS.length)return;pointerAt(e);const p=PARTS[currentRef.current],g=groups.get(p.id);if(!g||!ray.intersectObject(g,true)[0])return;dragging=p.id;controls.enabled=false;plane.constant=-p.target[1];if(ray.ray.intersectPlane(plane,point))offset.copy(g.position).sub(point);canvas.setPointerCapture(e.pointerId);setFeedback(`${p.name} selected — move it to the glowing real-world mounting location.`);e.preventDefault();e.stopPropagation()};const move=(e:PointerEvent)=>{if(!dragging)return;pointerAt(e);const p=PARTS.find(v=>v.id===dragging)!,g=groups.get(dragging)!;plane.constant=-p.target[1];if(ray.ray.intersectPlane(plane,point))g.position.set(point.x+offset.x,p.target[1],point.z+offset.z)};const up=(e:PointerEvent)=>{if(!dragging)return;const id=dragging;dragging=null;controls.enabled=true;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);const p=PARTS.find(v=>v.id===id)!,g=groups.get(id)!;const d=new THREE.Vector2(g.position.x-p.target[0],g.position.z-p.target[2]).length();if(d<=1.05){g.position.set(...p.target);const next=[...installedRef.current,id];installedRef.current=next;setInstalled(next);setFeedback(`Installed: ${p.name}. The next component is now highlighted.`);const n=Math.min(currentRef.current+1,PARTS.length-1);currentRef.current=n;setCurrent(n)}else{g.position.set(...p.start);setFeedback(`${p.name} is not aligned with its mounting point yet. Try again.`)}};canvas.addEventListener('pointerdown',down,{capture:true});canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);
 const resize=()=>{const w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()};const obs=new ResizeObserver(resize);obs.observe(canvas);resize();let frame=0;const draw=()=>{frame=requestAnimationFrame(draw);const a=PARTS[currentRef.current];for(const[id,g]of ghosts)g.visible=!installedRef.current.includes(id)&&id===a.id;for(const[id,g]of groups){const on=!installedRef.current.includes(id)&&id===a.id;g.traverse(o=>{if(o instanceof THREE.Mesh&&o.material instanceof THREE.MeshStandardMaterial){o.material.emissive.setHex(on?0x075b65:0);o.material.emissiveIntensity=on?.7:0}})}controls.update();renderer.render(scene,camera)};draw();return()=>{cancelAnimationFrame(frame);obs.disconnect();canvas.removeEventListener('pointerdown',down,true);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',up);controls.dispose();renderer.dispose()}},[session]);
 const reset=()=>{currentRef.current=0;installedRef.current=[];setCurrent(0);setInstalled([]);setFeedback('Rotate the real PC chassis, identify the glowing part, then install it in the highlighted location.');setSession(v=>v+1)};
 return <main className="assembly-lab"><header className="assembly-topbar"><button className="assembly-back" onClick={onBack}><ArrowLeft size={16}/> Computer Lab</button><div className="assembly-brand"><span className="assembly-brand-icon"><Wrench size={20}/></span><span><strong>Big Change PC Build Lab</strong><small>OPTIPLEX-STYLE SERVICE LAYOUT · BUILD STEP BY STEP</small></span></div><div className="assembly-progress-label">{installed.length} / {PARTS.length} installed</div></header><aside className="assembly-steps"><p className="assembly-eyebrow">BUILD ORDER</p><h1>{complete?'PC assembled!':active.name}</h1><p className="assembly-intro">{complete?'You installed the six core desktop components.':active.instruction}</p><div className="assembly-progress"><span style={{width:(installed.length/PARTS.length)*100+'%'}}/></div><div className="assembly-step-list">{PARTS.map((p,i)=>{const I=p.icon,done=installed.includes(p.id),on=!complete&&i===current;return <div key={p.id} className={'assembly-step '+(done?'done ':'')+(on?'active':'')}>{done?<CheckCircle2 size={17}/>:<I size={17}/>}<span>{p.name}</span></div>})}</div></aside><section className="assembly-stage"><canvas ref={canvasRef} aria-label="Interactive 3D desktop PC assembly lab."/><div className="assembly-stage-tip"><Rotate3D size={15}/> Empty space: rotate · Wheel: zoom · Glowing hardware: drag & install</div></section><aside className="assembly-detail" aria-live="polite"><p className="assembly-eyebrow">{complete?'SYSTEM READY':'LEARN THE PART'}</p><h2>{complete?'Desktop PC complete':active.name}</h2><p>{complete?'Rotate around your finished build, then rebuild it for another practice round.':active.why}</p><div className="assembly-feedback"><strong>Build coach</strong><p>{feedback}</p></div>{complete&&<button className="assembly-primary" onClick={reset}>Rebuild the PC <span>↻</span></button>}</aside></main>}
