import {
  concept,
  type Category,
  type Concept,
  type Entry,
} from '../concept.ts';
import type { SourceId } from '../sources.ts';

/**
 * The Intel Arc B580, as a third complete graphics card.
 *
 * The exterior follows Intel's own Limited Edition card. The chip scales follow
 * Intel's published Xe2 hierarchy: five render slices, four Xe-cores in each
 * slice, eight vector engines in each Xe-core, 160 vector engines in all.
 *
 * Every id carries an `arc` or `xe` prefix so nothing here collides with the
 * other two cards.
 */

const card =
  'Illustrative geometry after the Intel Arc B580 Limited Edition. The 272 × 115 mm dual-slot envelope, two 85 mm fans, four heat pipes, backplate cut-out, single 8-pin socket and four outputs follow Intel specifications and published teardowns; exact shapes, fin counts and routing are approximate.';
const board =
  'Representative placement on an illustrative board. Part families and counts follow published teardowns where one is cited; positions, values and routing are not a reproduction of Intel’s PCB.';
const architecture =
  'Documented Xe2 logical architecture from Intel. Block sizes and positions are illustrative; this is not a mask layout of BMG-G21.';
const shared =
  'Intel publishes this resource as a total for the whole GPU. The per-slice count shown divides that total evenly across the five render slices, which is an illustration rather than a published placement.';

const physicalCard = (
  e: Omit<Entry, 'level' | 'representationType'> & { sources: SourceId[] },
) =>
  concept({
    physicalAccuracy: card,
    ...e,
    level: 'arcb580',
    representationType: 'physical',
  });
const logicalChip = (
  e: Omit<Entry, 'representationType'> & { sources: SourceId[] },
) =>
  concept({
    physicalAccuracy: architecture,
    ...e,
    representationType: 'logical',
  });

export const arcConcepts: Concept[] = [
  // ── The card ─────────────────────────────────────────────────────────────
  concept({
    id: 'arccard',
    name: 'Intel Arc B580 Limited Edition',
    shortName: 'Arc B580',
    category: 'Graphics',
    parent: 'graphicscard',
    level: 'arcb580',
    open: 'arcb580',
    description:
      'Intel’s second-generation discrete graphics card, built around the Xe2 BMG-G21 processor.',
    purpose:
      'Renders games and runs AI and media work, with XMX matrix engines and dedicated ray tracing units.',
    quantity: '1 reference specimen',
    specifications: {
      Architecture: 'Xe2 (Battlemage)',
      GPU: 'BMG-G21',
      'Xe-cores': '20',
      Memory: '12 GB GDDR6 · 192-bit · 19 Gbps',
      'Total board power': '190 W',
      Interface: 'PCIe 4.0 ×8',
      Dimensions: '272 × 115 mm · 2 slots',
      Weight: '779 g',
    },
    representationType: 'physical',
    physicalAccuracy: card,
    sources: ['arcb580', 'arclaunch', 'arcreview'],
    searchTerms: [
      'intel',
      'arc',
      'b580',
      'battlemage',
      'xe2',
      'limited edition',
    ],
  }),
  physicalCard({
    id: 'arcshroud',
    name: 'Limited Edition shroud',
    shortName: 'Shroud',
    category: 'Cooling',
    parent: 'arccard',
    description:
      'A matte black cover with two round fan openings and no RGB lighting.',
    purpose: 'Holds the fans and guides their air into the fin stacks.',
    quantity: '1 modeled shroud',
    specifications: { Finish: 'Matte black' },
    sources: ['arcreview', 'arcteardown'],
    searchTerms: ['cover', 'exterior'],
  }),
  physicalCard({
    id: 'arcfan',
    name: 'Axial fans',
    shortName: 'Fan',
    category: 'Cooling',
    parent: 'arccard',
    description:
      'Two 85 mm fans with eleven blades each, their tips joined by an outer ring.',
    purpose:
      'Drive air through the fins. The fan past the end of the board blows straight through and out of the back.',
    quantity: '2 modeled fans',
    specifications: { Diameter: '85 mm', Blades: '11, ring-linked tips' },
    sources: ['arcteardown', 'arcreview'],
    searchTerms: ['cooling', 'airflow'],
  }),
  physicalCard({
    id: 'arcfanmotor',
    name: 'Brushless fan motors',
    shortName: 'Fan motor',
    category: 'Cooling',
    parent: 'arcfan',
    description: 'A wound stator and bearing under each fan hub.',
    purpose: 'Spin the impellers at the speed the board requests.',
    quantity: '2 modeled motors',
    specifications: { Type: 'Brushless DC, Hall-sensed' },
    sources: ['bldc'],
    searchTerms: ['stator', 'bearing', 'motor'],
  }),
  physicalCard({
    id: 'archeatsink',
    name: 'Fin stacks',
    shortName: 'Heatsink',
    category: 'Cooling',
    parent: 'arccard',
    description:
      'Two vertically oriented fin stacks threaded onto the heat pipes.',
    purpose: 'Release heat from the pipes into the fan air.',
    quantity: '1 complete assembly · 2 stacks',
    specifications: {
      Inventory: 'Both stacks stay together as one part',
      'Physical fin count': 'Not claimed',
    },
    sources: ['arcreview'],
    searchTerms: ['fins', 'radiator', 'heat sink'],
  }),
  physicalCard({
    id: 'archeatpipe',
    name: 'Heat pipes',
    shortName: 'Heat pipe',
    category: 'Cooling',
    parent: 'arccard',
    description:
      'Four sealed copper pipes from the cold plate into both fin stacks.',
    purpose:
      'Carry heat away from the processor by evaporation and condensation.',
    quantity: '4 heat pipes · approximate routing',
    specifications: { Count: '4', Routing: 'Approximate' },
    sources: ['arcteardown', 'arcreview'],
    searchTerms: ['heatpipe', 'copper'],
  }),
  physicalCard({
    id: 'arccoldplate',
    name: 'Copper cold plate',
    shortName: 'Cold plate',
    category: 'Cooling',
    parent: 'arccard',
    description: 'A copper plate that sits directly on the processor.',
    purpose: 'Draws heat out of the die and into the heat pipes.',
    quantity: '1 modeled plate',
    specifications: { Material: 'Copper' },
    sources: ['arcphotos', 'arcteardown'],
    searchTerms: ['cold plate', 'contact plate', 'copper'],
  }),
  physicalCard({
    id: 'arcbackplate',
    name: 'Flow-through backplate',
    shortName: 'Backplate',
    category: 'Cooling',
    parent: 'arccard',
    description:
      'A black rear plate with a large cut-out beyond the end of the board.',
    purpose:
      'Stiffens the card and lets the second fan’s air pass straight through the heatsink.',
    quantity: '1 modeled plate',
    specifications: { Opening: 'Flow-through cut-out' },
    sources: ['arcreview', 'arcteardown', 'arcphotos'],
    searchTerms: ['back plate', 'flow through', 'vent'],
  }),
  physicalCard({
    id: 'arclogo',
    name: 'Illuminated Arc logo',
    shortName: 'Logo light',
    category: 'Board',
    parent: 'arccard',
    description: 'A white LED Intel Arc mark on the top edge.',
    purpose: 'Lights when the card is powered; the only lighting on the card.',
    quantity: '1 modeled logo',
    specifications: { Colour: 'White' },
    sources: ['arcreview'],
    searchTerms: ['led', 'logo', 'lighting'],
  }),
  physicalCard({
    id: 'arcbracket',
    name: 'Display mounting bracket',
    shortName: 'I/O bracket',
    category: 'Board',
    parent: 'arccard',
    description: 'A dual-slot bracket carrying the display outputs.',
    purpose: 'Anchors the card to the case and locates its ports.',
    quantity: '1 modeled bracket',
    specifications: { Width: 'Two expansion slots' },
    sources: ['arcb580'],
    searchTerms: ['bracket', 'io'],
  }),
  physicalCard({
    id: 'arcfastener',
    name: 'Assembly fasteners',
    shortName: 'Fastener',
    category: 'Cooling',
    parent: 'arccard',
    description: 'Screws holding the shroud, cooler and backplate together.',
    purpose: 'Keep the cooler pressed evenly against the processor.',
    quantity: '8 modeled fasteners',
    specifications: { 'Count and placement': 'Illustrative' },
    sources: ['arcteardown'],
    searchTerms: ['screw', 'mounting'],
  }),
  physicalCard({
    id: 'arcthermalpad',
    name: 'Thermal pads',
    shortName: 'Thermal pad',
    category: 'Cooling',
    parent: 'arccard',
    description: 'Pads over the six memory chips and the voltage regulator.',
    purpose: 'Conduct heat from parts of different heights into the cooler.',
    quantity: '6 memory pads · illustrative',
    specifications: { Placement: 'Memory and VRM' },
    sources: ['arcteardown'],
    searchTerms: ['pad', 'thermal'],
  }),
  physicalCard({
    id: 'arctim',
    name: 'GPU thermal interface',
    shortName: 'GPU TIM',
    category: 'Cooling',
    parent: 'arccard',
    description: 'A thin layer between the die and the cold plate.',
    purpose: 'Fills microscopic gaps to lower thermal resistance.',
    quantity: '1 modeled layer',
    specifications: { Type: 'Illustrative' },
    sources: ['arcteardown'],
    searchTerms: ['thermal paste', 'tim'],
  }),
  physicalCard({
    id: 'arcretention',
    name: 'GPU retention bracket',
    shortName: 'Retention',
    category: 'Cooling',
    parent: 'arccard',
    description: 'A spring bracket behind the processor.',
    purpose: 'Spreads mounting pressure evenly across the package.',
    quantity: '1 modeled bracket',
    specifications: { Shape: 'Illustrative X bracket' },
    sources: ['arcteardown'],
    searchTerms: ['x bracket', 'spring'],
  }),
  physicalCard({
    id: 'arcstandoff',
    name: 'Mounting standoffs',
    shortName: 'Standoff',
    category: 'Board',
    parent: 'arccard',
    description: 'Threaded spacers around the processor.',
    purpose: 'Set the board-to-cooler gap so screws cannot bend the PCB.',
    quantity: '4 modeled standoffs',
    specifications: { Placement: 'Around the GPU package' },
    sources: ['arcteardown'],
    searchTerms: ['spacer', 'mount'],
  }),

  // ── The board ────────────────────────────────────────────────────────────
  physicalCard({
    id: 'arcpcb',
    name: 'Printed circuit board',
    shortName: 'PCB',
    category: 'Board',
    parent: 'arccard',
    description: 'An eight-layer board much shorter than the cooler above it.',
    purpose:
      'Routes power and signals, and ends early so air can pass through the rest of the card.',
    quantity: '1 illustrative board',
    specifications: { Layers: '8', 'Board outline': 'Short, illustrative' },
    physicalAccuracy: board,
    sources: ['arcteardown', 'arcphotos', 'packaging'],
    searchTerms: ['board', 'traces'],
  }),
  physicalCard({
    id: 'arcpackage',
    name: 'BMG-G21 GPU package',
    shortName: 'BMG-G21 package',
    category: 'Board',
    parent: 'arcpcb',
    open: 'bmg',
    description:
      'The substrate carrying the Battlemage die and fanning its connections out to the board.',
    purpose: 'Bridges the die’s bumps to board-scale power and signal traces.',
    quantity: '1 GPU package',
    specifications: {
      GPU: 'BMG-G21',
      Process: 'TSMC N5',
      'Device ID': '0xE20B',
    },
    physicalAccuracy: board,
    sources: ['arcb580'],
    searchTerms: ['gpu', 'processor', 'battlemage'],
  }),
  physicalCard({
    id: 'arcsilicon',
    name: 'Exposed BMG-G21 die',
    shortName: 'BMG-G21 die',
    category: 'Compute',
    parent: 'arcpackage',
    open: 'bmg',
    description: 'The Xe2 processor die, in the centre of the board.',
    purpose:
      'Holds the render slices, caches and interfaces. Its top face hands heat to the cold plate.',
    quantity: '1 die',
    specifications: { Process: 'TSMC N5' },
    physicalAccuracy: board,
    sources: ['arcb580', 'arcteardown'],
    searchTerms: ['silicon', 'chip', 'die'],
  }),
  physicalCard({
    id: 'arcbga',
    name: 'BGA solder connections',
    shortName: 'BGA',
    category: 'Board',
    parent: 'arcpackage',
    description: 'A grid of solder balls under the package.',
    purpose: 'Carry power and signals and fix the package to the board.',
    quantity: 'Representative ball grid',
    specifications: { 'Ball count': 'Illustrative' },
    physicalAccuracy: board,
    sources: ['packaging'],
    searchTerms: ['solder balls', 'ball grid array'],
  }),
  physicalCard({
    id: 'arcgddr6',
    name: 'GDDR6 memory',
    shortName: 'GDDR6',
    category: 'Memory',
    parent: 'arcpcb',
    description: 'Six Samsung 2 GB memory chips around the processor.',
    purpose: 'Hold textures, geometry and frame data.',
    quantity: '6 chips · 12 GB',
    specifications: {
      Capacity: '12 GB',
      Interface: '192-bit',
      'Data rate': '19 Gbps',
      Bandwidth: '456 GB/s',
    },
    physicalAccuracy: board,
    sources: ['arcb580', 'gddr6', 'arcphotos'],
    searchTerms: ['vram', 'ram', 'memory', 'framebuffer'],
  }),
  physicalCard({
    id: 'arcvrm',
    name: 'VRM chokes',
    shortName: 'Choke',
    category: 'Power',
    parent: 'arcpcb',
    description:
      'Shielded inductors for the six GPU phases and two memory phases.',
    purpose: 'Smooth each switching phase into steady current.',
    quantity: '8 chokes · 6 + 2 phases',
    specifications: { GPU: '6 phases', Memory: '2 phases' },
    physicalAccuracy: board,
    sources: ['arcteardown', 'arcreview', 'multiphase'],
    searchTerms: ['inductor', 'vrm', 'phases'],
  }),
  physicalCard({
    id: 'arcpowerstage',
    name: 'Switching power stages',
    shortName: 'Power stage',
    category: 'Power',
    parent: 'arcpcb',
    description: 'Driver and MOSFET packages, one per phase.',
    purpose: 'Switch 12 V input into the processor and memory supply rails.',
    quantity: '8 modeled stages',
    specifications: { 'Part number': 'Not asserted' },
    physicalAccuracy: board,
    sources: ['arcteardown', 'multiphase'],
    searchTerms: ['mosfet', 'drmos', 'vrm'],
  }),
  physicalCard({
    id: 'arcpwm',
    name: 'Multiphase controller',
    shortName: 'PWM controller',
    category: 'Power',
    parent: 'arcpcb',
    description: 'A controller that times every regulator phase.',
    purpose: 'Holds the supply voltages steady as load changes.',
    quantity: '1 modeled controller',
    specifications: { 'Part number': 'Not asserted' },
    physicalAccuracy: board,
    sources: ['multiphase'],
    searchTerms: ['pwm', 'voltage controller'],
  }),
  physicalCard({
    id: 'arccapacitor',
    name: 'Polymer capacitors',
    shortName: 'Capacitor',
    category: 'Power',
    parent: 'arcpcb',
    description: 'Solid capacitors at the regulator outputs.',
    purpose: 'Absorb rapid current changes so the voltage does not sag.',
    quantity: 'Illustrative components',
    specifications: { Placement: 'Approximate' },
    physicalAccuracy: board,
    sources: ['multiphase'],
    searchTerms: ['cap', 'capacitor'],
  }),
  physicalCard({
    id: 'arcmlcc',
    name: 'Ceramic decoupling capacitors',
    shortName: 'Ceramic capacitor',
    category: 'Power',
    parent: 'arcpcb',
    description: 'Tiny ceramic capacitors near fast-switching parts.',
    purpose: 'Suppress local supply noise.',
    quantity: 'Illustrative components',
    specifications: { 'Values and placement': 'Not asserted' },
    physicalAccuracy: board,
    sources: ['multiphase'],
    searchTerms: ['mlcc', 'decoupling'],
  }),
  physicalCard({
    id: 'arcresistor',
    name: 'Surface-mount resistors',
    shortName: 'Resistor',
    category: 'Board',
    parent: 'arcpcb',
    description: 'Small passive parts in control and signal circuits.',
    purpose: 'Set currents, bias voltages and terminations.',
    quantity: 'Illustrative components',
    specifications: { 'Values and placement': 'Not asserted' },
    physicalAccuracy: board,
    sources: ['multiphase'],
    searchTerms: ['resistor', 'smd'],
  }),
  physicalCard({
    id: 'arcpcie',
    name: 'PCIe edge connector',
    shortName: 'PCIe',
    category: 'Board',
    parent: 'arcpcb',
    description: 'Gold contacts on the lower edge of the board.',
    purpose: 'Carry data between the processor and the host over eight lanes.',
    quantity: '1 interface',
    specifications: { Link: 'PCI Express 4.0 ×8' },
    physicalAccuracy: board,
    sources: ['pcie', 'arcb580'],
    searchTerms: ['bus', 'slot', 'connector'],
  }),
  physicalCard({
    id: 'arcpower',
    name: '8-pin power connector',
    shortName: 'Power connector',
    category: 'Power',
    parent: 'arcpcb',
    description: 'A single 8-pin PCIe power socket.',
    purpose: 'Supplies power beyond what the slot delivers.',
    quantity: '1 socket',
    specifications: { Connector: '1 × 8-pin', 'Recommended PSU': '600 W' },
    physicalAccuracy: board,
    sources: ['arcb580', 'psu'],
    searchTerms: ['8 pin', 'pcie power'],
  }),
  physicalCard({
    id: 'arcbios',
    name: 'VBIOS flash memory',
    shortName: 'VBIOS',
    category: 'Board',
    parent: 'arcpcb',
    description: 'Serial flash holding the card’s firmware.',
    purpose: 'Stores start-up code and board configuration.',
    quantity: '1 modeled chip',
    specifications: { Placement: 'Illustrative' },
    physicalAccuracy: board,
    sources: ['flash'],
    searchTerms: ['bios', 'firmware', 'rom'],
  }),
  physicalCard({
    id: 'arcdisplayport',
    name: 'DisplayPort outputs',
    shortName: 'DisplayPort',
    category: 'Board',
    parent: 'arcpcb',
    description: 'Three DisplayPort 2.1 sockets.',
    purpose: 'Connect monitors: one port up to UHBR 13.5, two up to UHBR 10.',
    quantity: '3 DisplayPort 2.1',
    specifications: {
      Standard: 'DisplayPort 2.1',
      Rates: '1 × UHBR 13.5, 2 × UHBR 10',
    },
    physicalAccuracy: board,
    sources: ['arcb580'],
    searchTerms: ['dp', 'monitor output'],
  }),
  physicalCard({
    id: 'archdmi',
    name: 'HDMI output',
    shortName: 'HDMI',
    category: 'Board',
    parent: 'arcpcb',
    description: 'One HDMI 2.1 socket.',
    purpose: 'Connects TVs and monitors, up to 7680 × 4320 at 120 Hz.',
    quantity: '1 HDMI 2.1',
    specifications: { Standard: 'HDMI 2.1', VRR: 'Yes' },
    physicalAccuracy: board,
    sources: ['arcb580'],
    searchTerms: ['hdmi', 'display output'],
  }),
  physicalCard({
    id: 'arcfanheader',
    name: 'Fan header',
    shortName: 'Fan header',
    category: 'Board',
    parent: 'arcpcb',
    description: 'A keyed connector for the fan wiring.',
    purpose: 'Supplies fan power and reads back speed.',
    quantity: '1 modeled header',
    specifications: { Signals: 'Power, ground, tach, PWM' },
    physicalAccuracy: board,
    sources: ['mainboardmanual', 'bldc'],
    searchTerms: ['fan connector', 'pwm header'],
  }),
  physicalCard({
    id: 'arcfancable',
    name: 'Fan wiring harness',
    shortName: 'Fan cable',
    category: 'Cooling',
    parent: 'arccard',
    description: 'Insulated leads from both fan motors to the header.',
    purpose: 'Deliver power and carry the control and speed signals.',
    quantity: '2 modeled leads',
    specifications: { Routing: 'Illustrative' },
    sources: ['bldc'],
    searchTerms: ['cable', 'wire'],
  }),
  physicalCard({
    id: 'arctemperature',
    name: 'Temperature sensing IC',
    shortName: 'Temp sensor',
    category: 'Board',
    parent: 'arcpcb',
    description: 'A small sensor near the hot parts of the board.',
    purpose: 'Feeds fan control and thermal protection.',
    quantity: '1 illustrative sensor',
    specifications: { Placement: 'Not asserted' },
    physicalAccuracy: board,
    sources: ['temperature'],
    searchTerms: ['thermal sensor'],
  }),
  physicalCard({
    id: 'arcesd',
    name: 'ESD protection arrays',
    shortName: 'ESD',
    category: 'Board',
    parent: 'arcpcb',
    description: 'Protection diodes behind the display outputs.',
    purpose: 'Divert static discharges away from the display circuitry.',
    quantity: '4 illustrative arrays',
    specifications: { Placement: 'Behind the outputs' },
    physicalAccuracy: board,
    sources: ['esd'],
    searchTerms: ['tvs', 'esd', 'diode'],
  }),
  physicalCard({
    id: 'arccrystal',
    name: 'Reference clock crystal',
    shortName: 'Crystal',
    category: 'Board',
    parent: 'arcpcb',
    description: 'A quartz resonator near the processor.',
    purpose: 'Provides the timing reference the GPU clocks derive from.',
    quantity: '1 modeled crystal',
    specifications: { Placement: 'Approximate' },
    physicalAccuracy: board,
    sources: ['crystal'],
    searchTerms: ['oscillator', 'clock', 'quartz'],
  }),

  // ── BMG-G21 ──────────────────────────────────────────────────────────────
  logicalChip({
    id: 'arcgpu',
    name: 'BMG-G21 architecture',
    shortName: 'BMG-G21',
    category: 'Compute',
    parent: 'arcpackage',
    level: 'bmg',
    open: 'bmg',
    description:
      'An Xe2-HPG processor built from five render slices around a shared L2 cache and fixed-function engines.',
    purpose:
      'Runs graphics, ray tracing, AI and media work across 20 Xe-cores and 160 vector engines.',
    quantity: 'Arc B580 configuration',
    specifications: {
      'Render slices': '5',
      'Xe-cores': '20',
      'Vector engines': '160',
      'XMX engines': '160',
      'Ray tracing units': '20',
      'Graphics clock': '2,670 MHz',
      'Peak TOPS (INT8)': '233',
    },
    sources: ['arcb580', 'xe2deck', 'xearchitecture'],
    searchTerms: ['chip', 'silicon', 'xe2', 'battlemage'],
  }),
  logicalChip({
    id: 'xeslice',
    name: 'Render slice',
    shortName: 'Render slice',
    category: 'Compute',
    parent: 'arcgpu',
    level: 'bmg',
    open: 'xeslice',
    description: 'One of five repeated blocks that together make up the GPU.',
    purpose:
      'Packages Xe-cores with the texture and pixel hardware they need, so the design scales by adding or removing slices.',
    quantity: '5 on Arc B580',
    specifications: {
      'Xe-cores per slice': '4',
      'Arc A770 (Xe-HPG)': '8 slices',
    },
    sources: ['arcb580', 'xe2deck', 'xearchitecture'],
    searchTerms: ['all render slices', 'slice'],
  }),
  logicalChip({
    id: 'arcl2',
    name: 'L2 cache',
    shortName: 'L2 cache',
    category: 'Memory',
    parent: 'arcgpu',
    level: 'bmg',
    description: 'A shared on-chip cache used by all five render slices.',
    purpose: 'Keeps frequently used data between the cores and external GDDR6.',
    quantity: '18 MB',
    specifications: { Capacity: '18 MB' },
    sources: ['xe2deck'],
    searchTerms: ['cache', 'l2 memory'],
  }),
  logicalChip({
    id: 'arcmfx',
    name: 'Multi-format transcoders',
    shortName: 'Media engine',
    category: 'Graphics',
    parent: 'arcgpu',
    level: 'bmg',
    description: 'Two fixed-function Xe media engines for video.',
    purpose:
      'Encode and decode AV1, HEVC and H.264 video without using the vector engines.',
    quantity: '2 MFX engines',
    specifications: {
      Codecs: 'AV1, H.265 (HEVC), H.264 encode and decode',
      Also: 'VP9 support, HEVC 4:2:2 10-bit',
    },
    sources: ['xe2deck', 'arclaunch', 'arcb580'],
    searchTerms: ['video', 'encoder', 'decoder', 'mfx', 'av1'],
  }),
  logicalChip({
    id: 'arcdisplay',
    name: 'Display engine',
    shortName: 'Display engine',
    category: 'Graphics',
    parent: 'arcgpu',
    level: 'bmg',
    description: 'The block that scans finished frames out to the connectors.',
    purpose: 'Drives up to four displays over HDMI 2.1 and DisplayPort 2.1.',
    quantity: '1 functional group',
    specifications: { Displays: '4', 'Max HDMI': '7680 × 4320 at 120 Hz' },
    sources: ['arcb580'],
    searchTerms: ['display', 'scanout'],
  }),
  logicalChip({
    id: 'archost',
    name: 'PCIe host interface',
    shortName: 'PCIe interface',
    category: 'Board',
    parent: 'arcgpu',
    level: 'bmg',
    description: 'The on-chip endpoint for the link to the host.',
    purpose: 'Carries commands and data over eight PCIe 4.0 lanes.',
    quantity: '1 interface',
    specifications: { Link: 'PCIe 4.0 ×8' },
    sources: ['arcb580', 'pcie'],
    searchTerms: ['pcie', 'host', 'bus'],
  }),
  logicalChip({
    id: 'arcmemif',
    name: 'GDDR6 memory interface',
    shortName: 'Memory interface',
    category: 'Memory',
    parent: 'arcgpu',
    level: 'bmg',
    description: 'The controllers and PHY that drive the external GDDR6.',
    purpose: 'Move data to and from the 12 GB of memory on the board.',
    quantity: '1 interface',
    specifications: {
      Width: '192-bit',
      'Data rate': '19 Gbps',
      Bandwidth: '456 GB/s',
    },
    physicalAccuracy: `${architecture} Intel does not publish the number of memory controllers, so the interface is drawn as one block.`,
    sources: ['arcb580', 'xe2deck'],
    searchTerms: ['memory bus', 'gddr6 interface', 'memory controller'],
  }),

  // ── Render slice ─────────────────────────────────────────────────────────
  logicalChip({
    id: 'xecore',
    name: 'Xe-core',
    shortName: 'Xe-core',
    category: 'Compute',
    parent: 'xeslice',
    level: 'xeslice',
    open: 'xecore',
    description:
      'Intel’s basic compute block: eight vector engines, each with an XMX matrix engine, plus local cache.',
    purpose:
      'Runs shader and compute threads, and pairs with its own ray tracing unit.',
    quantity: '4 per slice · 20 on the GPU',
    specifications: {
      'Vector engines': '8',
      'XMX engines': '8',
      'L1 cache': '256 KB',
      SLM: '128 KB',
    },
    sources: ['xearchitecture', 'xe2deck', 'arcb580'],
    searchTerms: ['all xe-cores', 'xe core', 'core'],
  }),
  logicalChip({
    id: 'arcpixel',
    name: 'Pixel backends',
    shortName: 'Pixel backend',
    category: 'Graphics',
    parent: 'xeslice',
    level: 'xeslice',
    description: 'The final pixel stages of the graphics pipeline.',
    purpose:
      'Resolve covered pixels into the frame, blending and testing depth.',
    quantity: '2 per slice · 10 on the GPU',
    specifications: { 'GPU total': '10' },
    physicalAccuracy: `${architecture} ${shared}`,
    sources: ['xe2deck'],
    searchTerms: ['pixel', 'backend', 'blending'],
  }),
  logicalChip({
    id: 'arcsampler',
    name: 'Texture samplers',
    shortName: 'Sampler',
    category: 'Graphics',
    parent: 'xeslice',
    level: 'xeslice',
    description: 'Fixed-function hardware for reading and filtering textures.',
    purpose: 'Supply filtered surface detail to shaders.',
    quantity: '4 per slice · 20 on the GPU',
    specifications: { 'GPU total': '20' },
    physicalAccuracy: `${architecture} ${shared}`,
    sources: ['xe2deck'],
    searchTerms: ['texture', 'sampling', 'tmu'],
  }),

  // ── Xe-core ──────────────────────────────────────────────────────────────
  logicalChip({
    id: 'xve',
    name: 'Xe vector engine',
    shortName: 'XVE',
    category: 'Compute',
    parent: 'xecore',
    level: 'xecore',
    open: 'xve',
    description:
      'The programmable execution unit: 512-bit vector arithmetic with an XMX engine alongside.',
    purpose:
      'Executes shader and compute threads, issuing floating-point, integer and matrix work together.',
    quantity: '8 per Xe-core · 160 on the GPU',
    specifications: {
      'Register width': '512 bits',
      'Hardware threads': '8',
      'Sub-group sizes': '16, 32',
    },
    sources: ['xearchitecture', 'xe2deck', 'arcb580'],
    searchTerms: ['all vector engines', 'xve', 'execution unit', 'eu'],
  }),
  logicalChip({
    id: 'arcrtu',
    name: 'Ray tracing unit',
    shortName: 'RTU',
    category: 'Graphics',
    parent: 'xecore',
    level: 'xecore',
    description:
      'Dedicated traversal and intersection hardware paired with an Xe-core.',
    purpose: 'Walks BVH trees and tests rays against boxes and triangles.',
    quantity: '1 per Xe-core · 20 on the GPU',
    specifications: {
      'Box intersections': '18',
      'Triangle intersections': '2',
      'Traversal pipelines': '3',
      'BVH cache': '16 KB',
    },
    physicalAccuracy: `${architecture} Intel publishes 20 ray tracing units for 20 Xe-cores; drawing one beside each Xe-core follows that ratio rather than a published placement.`,
    sources: ['xe2deck', 'arcb580'],
    searchTerms: ['ray tracing', 'rt', 'bvh'],
  }),
  logicalChip({
    id: 'arcl1',
    name: 'L1 cache',
    shortName: 'L1 cache',
    category: 'Memory',
    parent: 'xecore',
    level: 'xecore',
    description: 'Fast local cache shared by the eight vector engines.',
    purpose: 'Keeps the data the core is working on within immediate reach.',
    quantity: '256 KB per Xe-core',
    specifications: { Capacity: '256 KB' },
    sources: ['xearchitecture', 'xe2deck'],
    searchTerms: ['l1', 'cache'],
  }),
  logicalChip({
    id: 'arcslm',
    name: 'Shared local memory',
    shortName: 'SLM',
    category: 'Memory',
    parent: 'xecore',
    level: 'xecore',
    description: 'Memory all threads in the core can read and write.',
    purpose:
      'Lets cooperating threads exchange results, with 64-bit atomic operations for safe updates.',
    quantity: '128 KB per Xe-core',
    specifications: { Capacity: '128 KB', 'Atomic ops': '64-bit' },
    sources: ['xearchitecture', 'xe2deck'],
    searchTerms: ['slm', 'shared memory', 'atomic'],
  }),
];

// ── Vector engine ────────────────────────────────────────────────────────────
const xveParts: [
  id: string,
  name: string,
  shortName: string,
  category: Category,
  description: string,
  purpose: string,
  quantity: string,
  specifications: Record<string, string>,
  searchTerms: string[],
][] = [
  [
    'arcalu',
    'SIMD16 arithmetic logic units',
    'ALU',
    'Compute',
    'Native 16-wide SIMD arithmetic across the 512-bit register.',
    'Performs the floating-point and integer arithmetic behind shaders and compute kernels.',
    '16 lanes per XVE',
    { Width: 'SIMD16 native, SIMD32 supported', Precision: 'FP32, FP64' },
    ['alu', 'simd', 'fp32', 'vector'],
  ],
  [
    'arcxmx',
    'XMX matrix engine',
    'XMX',
    'Compute',
    'A 2048-bit matrix engine for AI data types.',
    'Accelerates neural networks, including those behind XeSS upscaling and frame generation.',
    '1 per XVE · 160 on the GPU',
    { Width: '2048-bit', 'Data types': 'INT2, INT4, INT8, FP16, BF16, TF32' },
    ['ai', 'matrix', 'tensor', 'xess'],
  ],
  [
    'arcthread',
    'Hardware threads',
    'Thread',
    'Compute',
    'Independent execution contexts sharing the vector engine.',
    'Let one engine interleave several shader threads.',
    '8 per XVE',
    { Count: '8' },
    ['threads', 'smt'],
  ],
  [
    'arcregister',
    'General-purpose registers',
    'Register',
    'Memory',
    'Wide register storage for the values each thread is using.',
    'Keeps operands and results next to the arithmetic units.',
    '512-bit width',
    { Width: '512 bits' },
    ['registers', 'gpr'],
  ],
  [
    'arcem',
    'Extended math unit',
    'Extended math',
    'Compute',
    'Support for functions beyond basic arithmetic, including native double precision.',
    'Handles FP64 and extended math operations in the same issue as vector work.',
    'Functional group',
    { FP64: 'Native' },
    ['extended math', 'fp64', 'double precision'],
  ],
  [
    'arccoissue',
    'Three-way co-issue',
    'Co-issue',
    'Compute',
    'Issue logic that sends floating-point, integer or extended math, and XMX work together.',
    'Keeps all three kinds of execution resource busy on the same instruction stream.',
    'Functional group',
    { Paths: 'FP · INT/EM · XMX' },
    ['scheduler', 'dispatch', 'co-issue'],
  ],
];
const xveSources: Record<string, SourceId[]> = {
  arcalu: ['xe2deck', 'xearchitecture'],
  arcxmx: ['xe2deck', 'arcb580'],
  arcthread: ['xearchitecture'],
  arcregister: ['xearchitecture'],
  arcem: ['xe2deck', 'xearchitecture'],
  arccoissue: ['xe2deck'],
};
for (const [
  id,
  name,
  shortName,
  category,
  description,
  purpose,
  quantity,
  specifications,
  searchTerms,
] of xveParts)
  arcConcepts.push(
    logicalChip({
      id,
      name,
      shortName,
      category,
      parent: 'xve',
      level: 'xve',
      description,
      purpose,
      quantity,
      specifications,
      sources: xveSources[id],
      searchTerms,
    }),
  );
