import { concept, type Category, type Concept } from '../concept.ts';
import type { LevelId } from '../levels.ts';
import { sources } from '../sources.ts';

/**
 * The graphics card, unchanged.
 *
 * This is the original GPU catalogue, moved here verbatim when the project grew
 * from one card to a whole machine. The only edit is the root: `card` now hangs
 * off the PC's expansion slot instead of being the root of everything.
 */
export const gpuConcepts: Concept[] = [
  concept({
    id: 'card',
    name: 'ASUS TUF Gaming GeForce RTX 5090',
    shortName: 'RTX 5090',
    category: 'Graphics',
    // Was the root of the project. The card now hangs off the expansion slot
    // it is installed in, one branch of the whole machine.
    parent: 'graphicscard',
    level: 'card',
    open: 'card',
    description: 'An entire parallel computer on one graphics card.',
    purpose:
      'Turns electrical power and data into images, simulations and AI computation.',
    quantity: '1 reference specimen',
    specifications: {
      Architecture: 'Blackwell',
      GPU: 'GB202',
      'Graphics power': '575 W',
      Memory: '32 GB GDDR7',
      'Exterior reference': 'ASUS TUF Gaming',
      Dimensions: '348 × 146 × 72 mm · 3.6 slots',
    },
    representationType: 'physical',
  }),
  concept({
    id: 'shroud',
    name: 'Structural frame',
    category: 'Cooling',
    parent: 'card',
    level: 'card',
    description: 'The rigid surround that holds the cooler together.',
    purpose: 'Supports the fans and protects the fin array.',
    quantity: 'Illustrative frame',
    specifications: { Material: 'Metal / composite, illustrative' },
    representationType: 'physical',
    searchTerms: ['shroud', 'exterior'],
  }),
  concept({
    id: 'fan',
    name: 'Axial fans',
    shortName: 'Fan',
    category: 'Cooling',
    parent: 'card',
    level: 'card',
    description: 'Rotating blades move air across the cooler.',
    purpose: 'Carries heat from the fins into the surrounding air.',
    quantity: '3 modeled fans',
    specifications: {
      Design: 'Three Axial-tech fans; centre rotates oppositely',
    },
    representationType: 'physical',
    searchTerms: ['cooling', 'airflow'],
  }),
  concept({
    id: 'heatsink',
    name: 'Heatsink arrays',
    shortName: 'Heatsink',
    category: 'Cooling',
    parent: 'card',
    level: 'card',
    description:
      'Closely spaced metal fins expose a large surface to moving air.',
    purpose: 'Releases the heat collected from the processor and memory.',
    quantity: '1 complete assembly · 2 fin banks',
    specifications: { 'Fin spacing': 'Illustrative' },
    representationType: 'physical',
  }),
  concept({
    id: 'vapor',
    name: 'Vapor chamber',
    category: 'Cooling',
    parent: 'card',
    level: 'card',
    description:
      'A sealed heat spreader links the hot package to a larger cooling surface.',
    purpose: 'Spreads concentrated heat across the cooler.',
    quantity: '1 modeled assembly',
    specifications: { Geometry: 'Simplified heat transport' },
    representationType: 'physical',
    searchTerms: ['heatpipe', 'heat spreader'],
  }),
  concept({
    id: 'backplate',
    name: 'Backplate',
    category: 'Cooling',
    parent: 'card',
    level: 'card',
    description: 'The rear cover supports and protects the assembly.',
    purpose: 'Provides structure behind the circuit board.',
    quantity: '1 modeled plate',
    specifications: { Geometry: 'Approximate' },
    representationType: 'physical',
  }),
  concept({
    id: 'pcb',
    name: 'Printed circuit board',
    shortName: 'PCB',
    category: 'Board',
    parent: 'card',
    level: 'card',
    description: 'The electrical foundation connecting the card’s components.',
    purpose: 'Routes power and high-speed signals through copper layers.',
    quantity: '1 illustrative board',
    specifications: { 'Board outline': 'Educational approximation' },
    representationType: 'physical',
    searchTerms: ['board', 'traces'],
  }),
  concept({
    id: 'package',
    name: 'GB202 GPU package',
    shortName: 'GB202 package',
    category: 'Board',
    parent: 'pcb',
    level: 'card',
    open: 'die',
    description: 'The package connects the silicon processor to the board.',
    purpose:
      'Bridges microscopic chip connections to board-scale power and signals.',
    quantity: '1 GPU package',
    specifications: {
      GPU: 'GB202',
      'Die area': '750 mm²',
      Transistors: '92.2 billion',
    },
    representationType: 'physical',
    sources: ['whitepaper'],
    searchTerms: ['GPU', 'processor', 'silicon'],
  }),
  concept({
    id: 'gddr7',
    name: 'GDDR7 memory',
    shortName: 'GDDR7',
    category: 'Memory',
    parent: 'pcb',
    level: 'card',
    description: 'External memory holds the data that the GPU is working on.',
    purpose:
      'Stores textures, model weights, geometry and intermediate results.',
    quantity: '32 GB on the card',
    specifications: {
      Capacity: '32 GB',
      Interface: '512-bit',
      Bandwidth: '1,792 GB/s',
      'Data rate': '28 Gbps',
    },
    representationType: 'physical',
    searchTerms: ['VRAM', 'RAM', 'framebuffer'],
  }),
  concept({
    id: 'vrm',
    name: 'Voltage regulation',
    shortName: 'VRM',
    category: 'Power',
    parent: 'pcb',
    level: 'card',
    description:
      'Power stages convert the supply voltage for the processor and memory.',
    purpose: 'Provides stable low-voltage power as workloads change.',
    quantity: 'Illustrative power stages',
    specifications: { 'Stage count': 'Not specified by this model' },
    representationType: 'physical',
    searchTerms: ['VRM', 'power delivery', 'inductor'],
  }),
  concept({
    id: 'capacitor',
    name: 'Capacitors',
    category: 'Power',
    parent: 'pcb',
    level: 'card',
    description:
      'Small energy reservoirs sit close to power-hungry components.',
    purpose: 'Helps smooth rapid changes in voltage and current.',
    quantity: 'Illustrative passive components',
    specifications: { Placement: 'Approximate' },
    representationType: 'physical',
  }),
  concept({
    id: 'pcie',
    name: 'PCIe edge connector',
    shortName: 'PCIe',
    category: 'Board',
    parent: 'pcb',
    level: 'card',
    description: 'The card’s data connection to the host computer.',
    purpose:
      'Transfers commands and data between the GPU and the rest of the system.',
    quantity: '1 interface',
    specifications: { Interface: 'PCI Express 5.0' },
    representationType: 'physical',
    searchTerms: ['bus', 'connector'],
  }),
  concept({
    id: 'power',
    name: 'Power connector',
    category: 'Power',
    parent: 'pcb',
    level: 'card',
    description: 'The dedicated connection from the power supply.',
    purpose: 'Supplies power beyond what the motherboard slot can deliver.',
    quantity: '1 modeled connector',
    specifications: { 'Graphics power': '575 W total card rating' },
    representationType: 'physical',
    searchTerms: ['12V', '16 pin'],
  }),
  concept({
    id: 'die',
    name: 'GB202 architecture',
    shortName: 'GB202',
    category: 'Compute',
    parent: 'package',
    level: 'die',
    open: 'die',
    description: 'A hierarchy of parallel processing and memory resources.',
    purpose:
      'Coordinates thousands of execution resources on a single silicon die.',
    quantity: 'RTX 5090 enabled configuration',
    specifications: {
      GPCs: '11',
      TPCs: '85',
      SMs: '170',
      'CUDA cores': '21,760',
    },
    representationType: 'logical',
    searchTerms: ['chip', 'silicon', 'Blackwell'],
  }),
  concept({
    id: 'gpc',
    name: 'Graphics Processing Cluster',
    shortName: 'GPC',
    category: 'Compute',
    parent: 'die',
    level: 'die',
    open: 'gpc',
    description: 'A major cluster of graphics and compute resources.',
    purpose:
      'Groups processing clusters with raster and pixel-output hardware.',
    quantity: '11 enabled GPCs on RTX 5090',
    specifications: {
      'Full GPC': '8 TPCs / 16 SMs',
      'RTX 5090 total': '85 TPCs across 11 GPCs',
    },
    representationType: 'logical',
    searchTerms: ['all GPCs', 'cluster'],
  }),
  concept({
    id: 'l2',
    name: 'L2 cache',
    category: 'Memory',
    parent: 'die',
    level: 'die',
    description:
      'A shared pool of cached data between the chip and external memory.',
    purpose: 'Reduces repeated trips to GDDR7.',
    quantity: '96 MB on RTX 5090',
    specifications: { Capacity: '96 MB' },
    representationType: 'logical',
    searchTerms: ['cache', 'L2 memory'],
  }),
  concept({
    id: 'controller',
    name: 'Memory controllers',
    category: 'Memory',
    parent: 'die',
    level: 'die',
    description: 'The interfaces that manage communication with GDDR7.',
    purpose: 'Moves data between the processor and external memory.',
    quantity: '16 × 32-bit controllers',
    specifications: { 'Total interface': '512-bit' },
    representationType: 'logical',
    searchTerms: ['memory bus', 'interface'],
  }),
  concept({
    id: 'tpc',
    name: 'Texture Processing Cluster',
    shortName: 'TPC',
    category: 'Compute',
    parent: 'gpc',
    level: 'gpc',
    open: 'tpc',
    description:
      'A pair of streaming multiprocessors with geometry processing support.',
    purpose: 'Organizes programmable work into smaller processing clusters.',
    quantity: '85 enabled TPCs on RTX 5090',
    specifications: { 'SMs per TPC': '2', 'Full GPC': '8 TPCs' },
    representationType: 'logical',
    searchTerms: ['all TPCs'],
  }),
  concept({
    id: 'raster',
    name: 'Raster engine',
    category: 'Graphics',
    parent: 'gpc',
    level: 'gpc',
    description:
      'Converts projected triangles into fragments for pixel shading.',
    purpose: 'Connects geometric shapes to their coverage on the screen.',
    quantity: 'Per GPC',
    specifications: { Scope: 'Representative full GPC' },
    representationType: 'logical',
  }),
  concept({
    id: 'rop',
    name: 'Raster operations',
    shortName: 'ROPs',
    category: 'Graphics',
    parent: 'gpc',
    level: 'gpc',
    description:
      'The final pixel-processing resources in the graphics pipeline.',
    purpose: 'Performs operations such as blending and depth testing.',
    quantity: '176 ROPs on RTX 5090',
    specifications: { 'Full GPC': '2 partitions × 8 ROPs' },
    representationType: 'logical',
    searchTerms: ['pixel', 'blending'],
  }),
  concept({
    id: 'polymorph',
    name: 'PolyMorph engine',
    category: 'Graphics',
    parent: 'tpc',
    level: 'tpc',
    description: 'Geometry processing hardware associated with each TPC.',
    purpose: 'Supports fixed-function stages of geometric processing.',
    quantity: '1 per TPC',
    specifications: { Scope: 'TPC' },
    representationType: 'logical',
    searchTerms: ['geometry'],
  }),
  concept({
    id: 'sm',
    name: 'Streaming Multiprocessor',
    shortName: 'SM',
    category: 'Compute',
    parent: 'tpc',
    level: 'tpc',
    open: 'sm',
    description: 'The programmable workhorse of the GPU.',
    purpose:
      'Schedules groups of threads and supplies their execution and local memory resources.',
    quantity: '170 enabled SMs on RTX 5090',
    specifications: {
      'CUDA cores': '128 per SM',
      'Tensor cores': '4 per SM',
      'RT cores': '1 per SM',
    },
    representationType: 'logical',
    searchTerms: ['all SMs', 'multiprocessors'],
  }),
  concept({
    id: 'cuda',
    name: 'CUDA execution resources',
    shortName: 'CUDA core',
    category: 'Compute',
    parent: 'sm',
    level: 'sm',
    description:
      'Arithmetic execution resources used by programmable GPU threads.',
    purpose:
      'Performs the scalar arithmetic behind shaders and general-purpose GPU programs.',
    quantity: '128 per SM · 21,760 per card',
    specifications: { 'Per SM': '128', Arithmetic: 'Unified FP32 / INT32' },
    representationType: 'logical',
    searchTerms: ['all CUDA cores', 'FP32', 'INT32', 'ALU'],
  }),
  concept({
    id: 'tensor',
    name: 'Tensor cores',
    shortName: 'Tensor core',
    category: 'Compute',
    parent: 'sm',
    level: 'sm',
    description: 'Specialized execution resources for matrix operations.',
    purpose:
      'Accelerates the multiply-and-accumulate calculations used heavily in neural networks.',
    quantity: '4 per SM · 680 per card',
    specifications: {
      Generation: 'Fifth',
      'Per SM': '4',
      'Low precision': 'FP4 support',
    },
    representationType: 'logical',
    searchTerms: ['all Tensor Cores', 'AI', 'matrix', 'multiply'],
  }),
  concept({
    id: 'rt',
    name: 'Ray tracing core',
    shortName: 'RT core',
    category: 'Graphics',
    parent: 'sm',
    level: 'sm',
    description: 'Dedicated hardware for ray traversal and intersection work.',
    purpose: 'Accelerates finding where rays meet scene geometry.',
    quantity: '1 per SM · 170 per card',
    specifications: { Generation: 'Fourth', 'Per SM': '1' },
    representationType: 'logical',
    searchTerms: ['all RT cores', 'ray tracing', 'BVH'],
  }),
  concept({
    id: 'texture',
    name: 'Texture units',
    category: 'Graphics',
    parent: 'sm',
    level: 'sm',
    description: 'Hardware for reading and filtering texture data.',
    purpose: 'Provides sampled surface data to shaders.',
    quantity: '4 per SM · 680 per card',
    specifications: { 'Per SM': '4' },
    representationType: 'logical',
    searchTerms: ['TMU', 'sampling'],
  }),
  concept({
    id: 'scheduler',
    name: 'Warp schedulers',
    category: 'Compute',
    parent: 'sm',
    level: 'sm',
    description: 'Chooses eligible groups of threads to issue work.',
    purpose: 'Keeps execution resources supplied with ready instructions.',
    quantity: '4 processing partitions per SM',
    specifications: { 'Warp size': '32 threads' },
    representationType: 'logical',
    searchTerms: ['dispatch', 'scheduling', 'warp'],
  }),
  concept({
    id: 'register',
    name: 'Register files',
    category: 'Memory',
    parent: 'sm',
    level: 'sm',
    description: 'Very fast storage for the values each thread is using.',
    purpose: 'Keeps intermediate calculations close to execution resources.',
    quantity: '256 KB per SM',
    specifications: { 'Total per SM': '256 KB', Partitions: '4 × 64 KB' },
    representationType: 'logical',
    searchTerms: ['registers'],
  }),
  concept({
    id: 'l1',
    name: 'L1 cache / shared memory',
    shortName: 'L1 / shared',
    category: 'Memory',
    parent: 'sm',
    level: 'sm',
    description: 'Local storage shared by the work running on an SM.',
    purpose:
      'Reuses nearby data and lets cooperating threads exchange results.',
    quantity: '128 KB combined per SM',
    specifications: {
      'Combined capacity': '128 KB',
      'Shared / cache split': 'Configurable',
    },
    representationType: 'logical',
    searchTerms: ['L1', 'shared memory', 'cache'],
  }),
  concept({
    id: 'loadstore',
    name: 'Load / store units',
    shortName: 'Load / store',
    category: 'Memory',
    parent: 'sm',
    level: 'sm',
    description:
      'The pathway for moving thread data into and out of registers.',
    purpose: 'Executes memory accesses requested by instructions.',
    quantity: 'Grouped by processing partition',
    specifications: { View: 'Functional groups' },
    representationType: 'logical',
    searchTerms: ['LSU', 'memory access'],
  }),
  concept({
    id: 'sfu',
    name: 'Special function units',
    shortName: 'SFU',
    category: 'Compute',
    parent: 'sm',
    level: 'sm',
    description: 'Resources for specialized mathematical operations.',
    purpose: 'Supports functions such as transcendental approximations.',
    quantity: 'Grouped by processing partition',
    specifications: { View: 'Functional groups' },
    representationType: 'logical',
    searchTerms: ['math', 'special function'],
  }),
];
gpuConcepts.push(
  concept({
    id: 'thermalpad',
    name: 'Thermal interface pads',
    shortName: 'Thermal pad',
    category: 'Cooling',
    parent: 'card',
    level: 'card',
    description:
      'Compliant thermal material bridges small gaps between packages and the cooling assembly.',
    purpose:
      'Conducts heat while accommodating differences in component height.',
    quantity: '16 illustrative pads',
    specifications: { Placement: 'Educational approximation' },
    representationType: 'physical',
  }),
  concept({
    id: 'heatpipe',
    name: 'Heat transport pipes',
    shortName: 'Heat pipe',
    category: 'Cooling',
    parent: 'card',
    level: 'card',
    description:
      'Sealed thermal transport paths distribute heat across the fin arrays.',
    purpose: 'Carries heat away from the central heat pickup area.',
    quantity: '12 heatpipes · approximate routing',
    specifications: { Routing: 'Original approximate geometry' },
    representationType: 'physical',
  }),
  concept({
    id: 'powerstage',
    name: 'Switching power stages',
    shortName: 'Power stage',
    category: 'Power',
    parent: 'pcb',
    level: 'card',
    description:
      'Switching devices form part of the board’s voltage conversion circuitry.',
    purpose:
      'Regulates energy delivery together with inductors and capacitors.',
    quantity: '24 illustrative packages',
    specifications: { 'Electrical topology': 'Not asserted' },
    representationType: 'physical',
    searchTerms: ['MOSFET', 'driver', 'VRM'],
  }),
  concept({
    id: 'mlcc',
    name: 'Ceramic decoupling capacitors',
    shortName: 'Ceramic capacitor',
    category: 'Power',
    parent: 'pcb',
    level: 'card',
    description:
      'Small ceramic capacitors are placed near circuits that demand rapidly changing current.',
    purpose: 'Helps suppress local power-supply noise.',
    quantity: '64 illustrative components',
    specifications: { 'Values and placement': 'Not asserted' },
    representationType: 'physical',
    searchTerms: ['MLCC', 'decoupling'],
  }),
  concept({
    id: 'resistor',
    name: 'Surface-mount resistors',
    shortName: 'Resistor',
    category: 'Board',
    parent: 'pcb',
    level: 'card',
    description:
      'Small passive components support the board’s signal and control circuits.',
    purpose: 'Provides controlled resistance in supporting circuitry.',
    quantity: '64 illustrative components',
    specifications: { 'Values and placement': 'Not asserted' },
    representationType: 'physical',
  }),
  concept({
    id: 'fastener',
    name: 'Assembly fasteners',
    shortName: 'Fastener',
    category: 'Cooling',
    parent: 'card',
    level: 'card',
    description:
      'Mechanical fasteners secure the enclosure and cooling assemblies.',
    purpose: 'Maintains alignment and mechanical contact between components.',
    quantity: '16 modeled fasteners',
    specifications: { 'Count and placement': 'Illustrative' },
    representationType: 'physical',
    searchTerms: ['screw', 'mounting'],
  }),
  concept({
    id: 'bracket',
    name: 'Display mounting bracket',
    shortName: 'I/O bracket',
    category: 'Board',
    parent: 'card',
    level: 'card',
    description:
      'A rigid bracket supports the external ports and the card’s case mounting.',
    purpose: 'Locates display connections and anchors the card to the chassis.',
    quantity: '1 illustrative bracket',
    specifications: { Geometry: 'Approximate' },
    representationType: 'physical',
  }),
);
const fins = gpuConcepts.find((c) => c.id === 'heatsink')!;
fins.name = 'Heatsink assembly';
fins.shortName = 'Heatsink';
fins.quantity = '1 complete assembly · 2 fin banks';
fins.specifications = {
  Inventory: 'Fin banks stay together as one part',
  'Physical fin count': 'Not claimed for the reference card',
};
for (const id of [
  'card',
  'shroud',
  'fan',
  'heatsink',
  'vapor',
  'heatpipe',
  'backplate',
])
  gpuConcepts.find((c) => c.id === id)!.sources = ['tuf5090', 'tuf5090specs'];
// Component families found in modern graphics cards. These are representative
// educational assemblies, not an undocumented RTX 5090 bill of materials.
const boardParts: [
  string,
  string,
  Category,
  string,
  string,
  string,
  (keyof typeof sources)[],
  string[],
][] = [
  [
    'silicon',
    'Exposed GPU die',
    'Compute',
    'package',
    'The silicon chip contains the GPU’s transistors and on-chip interconnect.',
    'Executes graphics and compute work. Its exposed upper surface transfers heat to the cooler.',
    ['whitepaper'],
    ['silicon', 'processor', 'chip'],
  ],
  [
    'bga',
    'BGA solder connections',
    'Board',
    'package',
    'A grid of solder joints connects the package substrate to the PCB.',
    'Carries power, ground and signals while mechanically attaching the package to the board.',
    ['specs'],
    ['solder balls', 'ball grid array'],
  ],
  [
    'tim',
    'GPU thermal interface',
    'Cooling',
    'card',
    'A thin interface fills microscopic gaps between the die and the cooler’s contact surface.',
    'Reduces thermal contact resistance. ASUS documents a phase-change GPU thermal pad on the TUF RTX 5090.',
    ['construction'],
    ['thermal paste', 'liquid metal', 'TIM'],
  ],
  [
    'retention',
    'GPU retention spring',
    'Cooling',
    'card',
    'A spring bracket behind the GPU package distributes cooler mounting force.',
    'Maintains even contact pressure across the package and thermal interface.',
    ['specs'],
    ['x bracket', 'spring', 'retention bracket'],
  ],
  [
    'standoff',
    'Mounting standoffs',
    'Board',
    'card',
    'Threaded metal spacers set the distance between board and cooling assemblies.',
    'Prevents overtightening from bending the PCB and aligns the mounting screws.',
    ['specs'],
    ['spacer', 'mount'],
  ],
  [
    'pwm',
    'Multiphase PWM controllers',
    'Power',
    'pcb',
    'Control ICs coordinate the switching power stages in the GPU and memory regulators.',
    'Adjusts switching duty cycles and phase timing to hold the required supply voltage as load changes.',
    ['powerdesign'],
    ['voltage controller', 'PWM', 'VRM controller'],
  ],
  [
    'bios',
    'VBIOS flash memory',
    'Board',
    'pcb',
    'Nonvolatile serial flash stores the board firmware and configuration.',
    'Retains initialization information and board parameters even when the card is powered off.',
    ['flash'],
    ['BIOS', 'firmware', 'ROM', 'SPI'],
  ],
  [
    'shunt',
    'Current-sense shunts',
    'Power',
    'pcb',
    'Precision low-resistance elements sit in power paths.',
    'Produces a small voltage drop that monitoring circuitry uses to estimate current.',
    ['monitor'],
    ['current resistor', 'shunt'],
  ],
  [
    'monitor',
    'Power monitoring IC',
    'Power',
    'pcb',
    'A monitoring circuit measures supply voltages and current-sense signals.',
    'Reports power use and supports power-limit management and fault detection.',
    ['monitor'],
    ['telemetry', 'current sensor'],
  ],
  [
    'temperature',
    'Temperature sensing ICs',
    'Board',
    'pcb',
    'Small sensor circuits measure local or remote device temperature.',
    'Provides thermal feedback for fan control and protection. Exact sensor placement varies by board.',
    ['temperature'],
    ['thermal sensor', 'thermistor'],
  ],
  [
    'crystal',
    'Reference clock crystal',
    'Board',
    'pcb',
    'A quartz resonator provides a stable timing reference for clock circuitry.',
    'Helps establish the timing from which internal operating clocks are derived.',
    ['specs'],
    ['oscillator', 'clock', 'quartz'],
  ],
  [
    'fanheader',
    'Fan headers',
    'Board',
    'pcb',
    'Keyed board connectors attach the fan wiring.',
    'Carries fan power, ground, speed feedback and control signals.',
    ['specs'],
    ['fan connector', 'PWM header'],
  ],
  [
    'fancable',
    'Fan wiring harnesses',
    'Cooling',
    'card',
    'Insulated wires link each fan motor to its board connector.',
    'Delivers power and carries speed-control and tachometer signals.',
    ['specs'],
    ['cable', 'wire'],
  ],
  [
    'fanmotor',
    'Brushless fan motors',
    'Cooling',
    'fan',
    'A copper-wound stator and bearing assembly sits beneath each fan hub.',
    'Converts electrical energy into the torque that spins the fan impeller.',
    ['specs'],
    ['stator', 'bearing', 'motor'],
  ],
  [
    'fuse',
    'Input protection fuses',
    'Power',
    'pcb',
    'Protective elements can be placed in a card’s incoming supply paths.',
    'Interrupts excessive current during some faults. Population and protection design vary by card.',
    ['powerdesign'],
    ['fuse', 'protection'],
  ],
  [
    'esd',
    'ESD protection arrays',
    'Board',
    'pcb',
    'Protection devices sit near externally accessible signal connections.',
    'Shunts brief electrostatic discharge events away from sensitive circuitry.',
    ['specs'],
    ['TVS', 'ESD', 'diode'],
  ],
  [
    'auxreg',
    'Auxiliary voltage regulators',
    'Power',
    'pcb',
    'Small regulators generate supporting supply rails for board circuitry.',
    'Provides power for control, firmware and interface circuits alongside the main GPU and memory supplies.',
    ['powerdesign'],
    ['LDO', 'buck', 'auxiliary power'],
  ],
  [
    'testpoint',
    'Board test points',
    'Board',
    'pcb',
    'Exposed conductive pads provide access to selected electrical nets.',
    'Allows production equipment to probe signals and supplies during board testing.',
    ['specs'],
    ['test pad', 'debug'],
  ],
  [
    'displayport',
    'DisplayPort connectors',
    'Board',
    'pcb',
    'Shielded external connectors carry digital display signals.',
    'Connects monitors using DisplayPort 2.1b on the reference RTX 5090.',
    ['specs'],
    ['DP', 'monitor output'],
  ],
  [
    'hdmi',
    'HDMI connector',
    'Board',
    'pcb',
    'A shielded HDMI socket provides a digital audio and video output.',
    'Connects TVs and monitors using HDMI 2.1b on the reference RTX 5090.',
    ['specs'],
    ['HDMI', 'display output'],
  ],
];
for (const [
  id,
  name,
  category,
  parent,
  description,
  purpose,
  refs,
  searchTerms,
] of boardParts)
  gpuConcepts.push(
    concept({
      id,
      name,
      shortName: name,
      category,
      parent,
      level: 'card',
      description,
      purpose,
      quantity: 'Representative component family',
      specifications: { 'Model scope': 'Illustrative geometry and population' },
      representationType: 'physical',
      sources: refs,
      searchTerms,
      ...(id === 'silicon' ? { open: 'die' as LevelId } : {}),
    }),
  );
const inductor = gpuConcepts.find((c) => c.id === 'vrm')!;
for (const id of ['hdmi', 'displayport', 'power'])
  gpuConcepts.find((c) => c.id === id)!.sources = ['tuf5090specs'];
gpuConcepts.find((c) => c.id === 'hdmi')!.quantity = '2 HDMI 2.1b ports';
gpuConcepts.find((c) => c.id === 'displayport')!.quantity =
  '3 DisplayPort 2.1b ports';
inductor.name = 'VRM inductors / chokes';
inductor.shortName = 'Inductor';
inductor.description =
  'Shielded inductors store energy in a magnetic field as the power stages switch.';
inductor.purpose =
  'Smooths the switched current into a steady supply for the GPU and memory, together with the output capacitors.';
inductor.quantity = '12 illustrative inductors';
inductor.sources = ['powerdesign'];
for (const [id, name, description, purpose, quantity] of [
  [
    'nvenc',
    'NVENC video encoders',
    'Dedicated video compression engines on the GPU.',
    'Encodes video for recording, streaming and export without using shader cores for the entire compression process.',
    '3 ninth-generation encoders',
  ],
  [
    'nvdec',
    'NVDEC video decoders',
    'Dedicated engines for decompressing supported video formats.',
    'Turns compressed video into frames for playback and editing.',
    '2 sixth-generation decoders',
  ],
  [
    'displayengine',
    'Display engine',
    'The on-chip pipeline that scans out completed images.',
    'Feeds display timing, pixels and audio to the external display interfaces.',
    'Functional group',
  ],
  [
    'host',
    'PCIe host interface',
    'The on-chip endpoint for the connection to the host computer.',
    'Receives commands and transfers data over the PCIe bus.',
    'PCIe 5.0 interface',
  ],
  [
    'command',
    'Command front end',
    'The GPU’s front end receives and dispatches submitted work.',
    'Directs graphics and compute work toward the appropriate processing resources.',
    'Functional group',
  ],
] as const)
  gpuConcepts.push(
    concept({
      id,
      name,
      shortName: name,
      description,
      purpose,
      quantity,
      category: id === 'host' ? 'Board' : 'Graphics',
      parent: 'die',
      level: 'die',
      representationType: 'logical',
      specifications: { View: 'Logical functional group' },
      searchTerms: [
        id,
        'video',
        ...(id === 'nvenc' ? ['encoder'] : id === 'nvdec' ? ['decoder'] : []),
      ],
      sources: id === 'command' ? ['whitepaper'] : ['specs'],
    }),
  );

// Manufacturer architecture and circuit references for the modeled part families.
// Circuit examples are not a bill of materials for the ASUS card.
const componentReferences: Record<string, (keyof typeof sources)[]> = {
  fuse: ['fuse'],
  pcb: ['tuf5090', 'packaging'],
  gddr7: ['whitepaper'],
  capacitor: ['multiphase'],
  pcie: ['pcie', 'tuf5090specs'],
  thermalpad: ['tuf5090'],
  powerstage: ['multiphase'],
  mlcc: ['multiphase'],
  resistor: ['multiphase'],
  fastener: ['tuf5090'],
  bracket: ['tuf5090'],
  bga: ['packaging'],
  tim: ['tuf5090'],
  retention: ['tuf5090'],
  standoff: ['tuf5090'],
  crystal: ['crystal'],
  fanheader: ['mainboardmanual', 'bldc'],
  fancable: ['mainboardmanual', 'bldc'],
  fanmotor: ['bldc'],
  esd: ['esd'],
  testpoint: ['acdc'],
  nvenc: ['whitepaper'],
  nvdec: ['whitepaper'],
  displayengine: ['whitepaper'],
  host: ['whitepaper', 'pcie'],
};
for (const entry of gpuConcepts) {
  if (componentReferences[entry.id])
    entry.sources = componentReferences[entry.id];
}
