import { concept, standard, type Concept } from '../concept.ts';

/**
 * Inside the mainboard.
 *
 * Slot positions, board outline and the rear aperture follow the ATX
 * specification. The major zones follow the supplied X670E reference while
 * controller identities, regulator phase count and electrical routing remain
 * representative rather than a product netlist or exact board reproduction.
 */
export const motherboardConcepts: Concept[] = [
  concept({
    id: 'moboboard',
    name: 'Mainboard substrate',
    shortName: 'Board',
    category: 'Board',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'A multi-layer fibreglass board with copper planes and routed signal layers between them.',
    purpose:
      'Carries every signal and supply rail on the board, with ground planes that keep high-speed links intact.',
    quantity: '1 ATX board',
    specifications: {
      Outline: '305 × 244 mm',
      Layers: 'Multi-layer, illustrative stack',
    },
    representationType: 'physical',
    physicalAccuracy: standard,
    sources: ['mainboardmanual'],
    searchTerms: ['pcb', 'substrate', 'traces', 'layers'],
  }),
  concept({
    id: 'socket',
    name: 'Processor socket',
    shortName: 'Socket',
    category: 'Board',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'A land-grid array of spring contacts under a lever-operated retention frame.',
    purpose:
      'Presses hundreds of contacts against the processor’s pads so it can be installed without soldering.',
    quantity: '1 modeled socket',
    specifications: {
      Type: 'AMD AM5 land grid array, illustrative',
      Retention: 'Lever and load plate',
    },
    representationType: 'physical',
    sources: ['mainboardmanual', 'ryzen'],
    searchTerms: ['am5', 'lga', 'socket', 'retention', 'contacts', 'zif'],
  }),
  concept({
    id: 'cpu',
    name: 'Central processing unit',
    shortName: 'CPU',
    category: 'Compute',
    parent: 'socket',
    level: 'motherboard',
    open: 'ryzen',
    description:
      'The general-purpose processor: a small number of very fast, very flexible cores.',
    purpose:
      'Runs the operating system and program logic, and decides what every other part of the machine does next.',
    quantity: '1 processor package',
    specifications: {
      Package: 'AMD AM5 land grid array',
      Lid: 'Integrated heat spreader',
    },
    representationType: 'physical',
    sources: ['ryzen', 'zen5'],
    searchTerms: ['processor', 'cpu', 'chip', 'core', 'package'],
  }),
  concept({
    id: 'dimmslot',
    name: 'Memory slots',
    shortName: 'DIMM slot',
    category: 'Memory',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'Keyed edge connectors with latches, wired as two channels of two slots.',
    purpose:
      'Connects memory modules to the processor’s memory controller on length-matched traces.',
    quantity: '4 modeled slots',
    specifications: { Contacts: '288-pin DDR5', Channels: '2' },
    representationType: 'physical',
    physicalAccuracy: standard,
    sources: ['mainboardmanual', 'ddr5architecture'],
    searchTerms: ['dimm', 'slot', 'memory', 'channel'],
  }),
  concept({
    id: 'ram',
    name: 'Memory modules',
    shortName: 'RAM',
    category: 'Memory',
    parent: 'dimmslot',
    level: 'motherboard',
    description:
      'DDR5 modules: rows of memory chips on a small board, with their own power management on board.',
    purpose:
      'Holds the code and data the processor is working on right now. It is fast, plentiful and erased at power-off.',
    quantity: '2 modeled modules',
    specifications: {
      Standard: 'DDR5',
      Contacts: '288-pin',
      'Sub-channels': '2 per module',
    },
    representationType: 'physical',
    physicalAccuracy: standard,
    sources: ['ddr5architecture', 'ddr5'],
    searchTerms: ['ram', 'ddr5', 'memory', 'dimm', 'module'],
  }),
  concept({
    id: 'chipset',
    name: 'Chipset',
    category: 'Board',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'A support processor that fans one link from the processor out into many slower ones.',
    purpose:
      'Provides the extra PCIe lanes, SATA ports and USB controllers the processor does not expose directly.',
    quantity: '1 modeled device',
    specifications: {
      Role: 'Platform I/O hub',
      Cooling: 'Passive heatsink',
    },
    representationType: 'physical',
    sources: ['mainboardmanual'],
    searchTerms: ['chipset', 'southbridge', 'phc', 'hub', 'io'],
  }),
  concept({
    id: 'uefi',
    name: 'UEFI firmware flash',
    shortName: 'BIOS / UEFI',
    category: 'Board',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'A small non-volatile flash chip holding the firmware that runs before any operating system exists.',
    purpose:
      'Brings the board up from cold, trains memory, enumerates devices and hands control to a bootloader.',
    quantity: '1 modeled flash device',
    specifications: { Type: 'Serial flash', Interface: 'SPI' },
    representationType: 'physical',
    sources: ['flash'],
    searchTerms: ['bios', 'uefi', 'firmware', 'flash', 'boot', 'spi'],
  }),
  concept({
    id: 'cmos',
    name: 'CMOS battery',
    shortName: 'Battery',
    category: 'Board',
    parent: 'motherboard',
    level: 'motherboard',
    description: 'A coin cell in a clip beside the firmware flash.',
    purpose:
      'Keeps the real-time clock and a small block of firmware settings alive while the machine is unplugged.',
    quantity: '1 modeled cell',
    specifications: { Type: 'Lithium coin cell' },
    representationType: 'physical',
    sources: ['mainboardmanual'],
    searchTerms: ['battery', 'cmos', 'clock', 'rtc', 'coin cell'],
  }),
  concept({
    id: 'pcie16',
    name: 'PCIe ×16 slots',
    shortName: 'PCIe ×16',
    category: 'Board',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'Long expansion slots with a retention latch, wired with up to sixteen lanes.',
    purpose:
      'Gives a graphics card or accelerator a wide, direct, high-bandwidth path to the processor.',
    quantity: '2 modeled slots',
    specifications: {
      Generation: 'PCI Express 5.0',
      'Per-lane rate': '32 GT/s',
      Lanes: 'Up to ×16',
    },
    representationType: 'physical',
    physicalAccuracy: standard,
    sources: ['mainboardmanual', 'pcie'],
    searchTerms: ['pcie', 'slot', 'expansion', 'x16', 'graphics'],
  }),
  concept({
    id: 'pcie1',
    name: 'PCIe ×1 slots',
    shortName: 'PCIe ×1',
    category: 'Board',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'Short single-lane slots for capture, network and audio cards.',
    purpose:
      'Adds expansion for devices that need a modest amount of bandwidth.',
    quantity: '2 modeled slots',
    specifications: { Generation: 'PCI Express', Lanes: '×1' },
    representationType: 'physical',
    sources: ['mainboardmanual', 'pcie'],
    searchTerms: ['pcie', 'x1', 'slot', 'expansion'],
  }),
  concept({
    id: 'm2slot',
    name: 'M.2 sockets',
    shortName: 'M.2 socket',
    category: 'Storage',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'Flat edge sockets between the expansion slots, each under a thermal cover.',
    purpose:
      'Connects a solid-state drive straight to PCIe lanes with no cable and no drive bay.',
    quantity: '2 modeled sockets',
    specifications: { Format: '2280', Interface: 'PCIe' },
    representationType: 'physical',
    physicalAccuracy: standard,
    sources: ['mainboardmanual', 'samsungnvme'],
    searchTerms: ['m.2', 'm2', 'socket', 'nvme', 'ssd'],
  }),
  concept({
    id: 'nvme',
    open: 'nvme',
    name: 'NVMe solid-state drive',
    shortName: 'NVMe SSD',
    category: 'Storage',
    parent: 'm2slot',
    level: 'motherboard',
    description:
      'Flash packages and a controller on a bare card, speaking NVMe over PCIe.',
    purpose:
      'Stores the operating system and data with far more parallelism than the older SATA command set allowed.',
    quantity: '1 modeled drive',
    specifications: {
      Architecture: 'Bare module · motherboard edge connector',
      Protocol: 'NVM Express',
      Interface: 'PCIe ×4',
      Format: 'M.2 2280',
      Dimensions: '80 × 22 mm',
    },
    representationType: 'physical',
    physicalAccuracy: standard,
    sources: ['samsungnvme', 'ssdarchitecture', 'nvme'],
    searchTerms: ['nvme', 'ssd', 'm.2', 'storage', 'flash', 'drive'],
  }),
  concept({
    id: 'm2heatsink',
    name: 'M.2 thermal covers',
    shortName: 'M.2 cover',
    category: 'Cooling',
    parent: 'm2slot',
    level: 'motherboard',
    description: 'Finned plates clamped over the drives on a thermal pad.',
    purpose:
      'Draws heat off the controller so sustained writes do not force the drive to slow itself down.',
    quantity: '2 modeled covers',
    specifications: { Contact: 'Thermal pad' },
    representationType: 'physical',
    sources: ['mainboardmanual'],
    searchTerms: ['heatsink', 'cover', 'thermal', 'm.2'],
  }),
  concept({
    id: 'cpuvrm',
    name: 'Processor voltage regulator',
    shortName: 'CPU VRM',
    category: 'Power',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'Switching power stages, inductors and capacitors in a row along the top and left of the socket.',
    purpose:
      'Steps 12 V down to the processor’s core voltage and holds it steady through very fast load swings.',
    quantity: '14 modeled phases',
    specifications: {
      Topology: 'Multiphase buck, illustrative',
      Input: '+12 V',
    },
    representationType: 'physical',
    sources: ['multiphase', 'mainboardmanual'],
    searchTerms: ['vrm', 'power', 'phase', 'regulator', 'buck', 'mosfet'],
  }),
  concept({
    id: 'vrmheatsink',
    name: 'VRM heatsinks',
    shortName: 'VRM heatsink',
    category: 'Cooling',
    parent: 'cpuvrm',
    level: 'motherboard',
    description: 'Finned aluminium blocks over the power stages.',
    purpose:
      'Keeps the switching devices within their rated temperature at sustained high current.',
    quantity: '2 modeled heatsinks',
    specifications: { Contact: 'Thermal pad' },
    representationType: 'physical',
    sources: ['mainboardmanual'],
    searchTerms: ['heatsink', 'vrm', 'cooling', 'fins'],
  }),
  concept({
    id: 'atx24',
    name: '24-pin board power connector',
    shortName: '24-pin',
    category: 'Power',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'The tall keyed connector on the right edge that the main supply loom plugs into.',
    purpose:
      'Brings the supply’s main rails onto the board, along with the signals that switch it on and report readiness.',
    quantity: '1 modeled connector',
    specifications: { Contacts: '24', Rails: '+12 V · +5 V · +3.3 V' },
    representationType: 'physical',
    physicalAccuracy: standard,
    sources: ['psu'],
    searchTerms: ['24-pin', 'atx', 'power', 'connector'],
  }),
  concept({
    id: 'eps8',
    name: 'Processor power connectors',
    shortName: 'EPS 8-pin',
    category: 'Power',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'Eight-pin connectors at the top edge feeding the regulator directly.',
    purpose:
      'Delivers high current to the processor’s regulator on conductors sized for it, separate from the main loom.',
    quantity: '2 modeled connectors',
    specifications: { Contacts: '8 per connector', Rail: '+12 V' },
    representationType: 'physical',
    sources: ['psu'],
    searchTerms: ['eps', '8-pin', 'cpu power', 'connector'],
  }),
  concept({
    id: 'sataport',
    name: 'SATA ports',
    shortName: 'SATA port',
    category: 'Storage',
    parent: 'motherboard',
    level: 'motherboard',
    description: 'Right-angle L-keyed connectors along the board’s right edge.',
    purpose: 'Connects drives in the cage to the chipset’s storage controller.',
    quantity: '4 modeled ports',
    specifications: { Rate: '6 Gb/s' },
    representationType: 'physical',
    physicalAccuracy: standard,
    sources: ['mainboardmanual', 'sata'],
    searchTerms: ['sata', 'port', 'drive', 'connector', 'storage'],
  }),
  concept({
    id: 'reario',
    name: 'Rear I/O stack',
    shortName: 'Rear I/O',
    category: 'Board',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'The block of external connectors that shows through the back of the case.',
    purpose:
      'Connects the machine to everything outside it: peripherals, network, audio and displays.',
    quantity: '1 modeled stack',
    specifications: { Aperture: '158.75 × 44.45 mm' },
    representationType: 'physical',
    physicalAccuracy: standard,
    sources: ['mainboardmanual'],
    searchTerms: ['usb', 'ethernet', 'audio', 'ports', 'rear', 'io'],
  }),
  concept({
    id: 'lan',
    name: 'Network controller',
    shortName: 'Ethernet',
    category: 'Board',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'A controller beside the rear jack, with its magnetics between it and the socket.',
    purpose:
      'Turns packets into signals on twisted-pair cabling, isolated from the board electrically.',
    quantity: '1 modeled controller',
    specifications: { Interface: 'Wired Ethernet' },
    representationType: 'physical',
    sources: ['mainboardmanual'],
    searchTerms: ['ethernet', 'lan', 'network', 'nic', 'rj45'],
  }),
  concept({
    id: 'audiocodec',
    name: 'Audio codec',
    shortName: 'Audio',
    category: 'Board',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'A converter in a partitioned corner of the board, often with its own ground island.',
    purpose:
      'Converts between digital audio and the analogue signals the rear jacks carry.',
    quantity: '1 modeled codec',
    specifications: { Isolation: 'Separated ground area' },
    representationType: 'physical',
    sources: ['mainboardmanual'],
    searchTerms: ['audio', 'codec', 'sound', 'jack', 'analog'],
  }),
  concept({
    id: 'superio',
    name: 'Sensor and fan controller',
    shortName: 'Sensor hub',
    category: 'Board',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'A small controller that reads temperatures and drives the fan headers.',
    purpose:
      'Runs the fan curves and reports board voltages and temperatures to firmware and the operating system.',
    quantity: '1 modeled controller',
    specifications: { Role: 'Monitoring and fan control' },
    representationType: 'physical',
    sources: ['mainboardmanual', 'temperature'],
    searchTerms: ['super i/o', 'sensor', 'fan control', 'monitoring', 'pwm'],
  }),
  concept({
    id: 'mobofanheader',
    name: 'Fan headers',
    shortName: 'Fan header',
    category: 'Cooling',
    parent: 'motherboard',
    level: 'motherboard',
    description: 'Four-pin posts scattered around the board edges.',
    purpose:
      'Powers each fan and gives it a speed command while reading its tachometer back.',
    quantity: '6 modeled headers',
    specifications: { Contacts: '4-pin PWM' },
    representationType: 'physical',
    sources: ['mainboardmanual', 'bldc'],
    searchTerms: ['fan', 'header', 'pwm', 'connector'],
  }),
  concept({
    id: 'frontheader',
    name: 'Front-panel headers',
    shortName: 'Front header',
    category: 'Board',
    parent: 'motherboard',
    level: 'motherboard',
    description:
      'Pin blocks along the bottom edge for the case’s buttons, LEDs and front ports.',
    purpose:
      'Brings the power button, activity lights and front connectors back to the board.',
    quantity: '4 modeled headers',
    specifications: { Types: 'Front panel · USB · audio' },
    representationType: 'physical',
    sources: ['mainboardmanual'],
    searchTerms: ['header', 'front panel', 'usb', 'power button'],
  }),
];
