import {
  concept,
  type Category,
  type Concept,
  type Entry,
} from '../concept.ts';
import type { SourceId } from '../sources.ts';

/**
 * The AMD Radeon RX 9070 XT, as a second complete graphics card.
 *
 * The exterior and board follow the Sapphire NITRO+ RX 9070 XT, because AMD
 * did not sell a card of its own for this GPU. The chip scales follow AMD's own
 * description of RDNA 4 at Hot Chips 2025 and the RX 9070 XT specification
 * page: four shader engines, eight workgroup processors in each, two compute
 * units in each workgroup processor, 64 compute units in all.
 *
 * Every id carries an `rx` prefix so that nothing here can collide with the
 * RTX 5090 catalogue, which uses bare names such as `fan` and `pcb`.
 */

const card =
  'Illustrative geometry after the Sapphire NITRO+ RX 9070 XT. The 330.8 × 128.5 × 65.7 mm envelope, three fans, six heat pipes, magnetic backplate, rear power socket and four outputs follow published descriptions; exact shapes, fin counts and routing are approximate.';
const board =
  'Representative placement on an illustrative board. Part families and counts follow the published NITRO+ teardown where one is cited; positions, values and routing are not a reproduction of the Sapphire PCB.';
const architecture =
  'Documented RDNA 4 logical architecture from AMD. Block sizes and positions are illustrative; this is not a mask layout of Navi 48.';
const interpretive =
  'AMD publishes the contents of the compute engine as one diagram. Which of those blocks belong to the workgroup processor and which to each compute unit is drawn here as an interpretation of that diagram, not as a claim of exact partitioning.';

const physicalCard = (
  e: Omit<Entry, 'level' | 'representationType'> & { sources: SourceId[] },
) =>
  concept({
    physicalAccuracy: card,
    ...e,
    level: 'rx9070',
    representationType: 'physical',
  });
const logicalChip = (
  e: Omit<Entry, 'representationType'> & { sources: SourceId[] },
) =>
  concept({
    physicalAccuracy: architecture,
    ...e,
    representationType: 'logical',
  });

export const radeonConcepts: Concept[] = [
  // ── The card ─────────────────────────────────────────────────────────────
  concept({
    id: 'rxcard',
    name: 'Sapphire NITRO+ Radeon RX 9070 XT',
    shortName: 'RX 9070 XT',
    category: 'Graphics',
    parent: 'graphicscard',
    level: 'rx9070',
    open: 'rx9070',
    description:
      'AMD’s RDNA 4 graphics card, a single Navi 48 processor with 16 GB of GDDR6 around it.',
    purpose:
      'Renders games and runs parallel compute and machine-learning work, with dedicated hardware for ray tracing and matrix math.',
    quantity: '1 reference specimen',
    specifications: {
      Architecture: 'RDNA 4',
      GPU: 'Navi 48',
      'Compute units': '64',
      Memory: '16 GB GDDR6 · 256-bit · 20 Gbps',
      'Total board power': '304 W AMD specification',
      Interface: 'PCIe 5.0 ×16',
      'Exterior reference': 'Sapphire NITRO+',
      Dimensions: '330.8 × 128.5 × 65.7 mm',
    },
    representationType: 'physical',
    physicalAccuracy: card,
    sources: ['rx9070xt', 'nitro9070', 'nitroteardown'],
    searchTerms: ['radeon', 'amd', '9070', 'rdna 4', 'sapphire', 'nitro'],
  }),
  physicalCard({
    id: 'rxshroud',
    name: 'NITRO+ shroud',
    shortName: 'Shroud',
    category: 'Cooling',
    parent: 'rxcard',
    description:
      'A gun-metal grey cover with perforated panels and a grille over the exposed fins.',
    purpose:
      'Holds the three fans in place, directs their air into the heatsink and protects the fin edges.',
    quantity: '1 modeled shroud',
    specifications: { Finish: 'Gun-metal grey with perforations' },
    sources: ['nitro9070', 'nitroteardown'],
    searchTerms: ['cover', 'exterior', 'grille'],
  }),
  physicalCard({
    id: 'rxfan',
    name: 'AeroCurve fans',
    shortName: 'Fan',
    category: 'Cooling',
    parent: 'rxcard',
    description:
      'Three 100 mm axial fans with smooth, curved AeroCurve blades.',
    purpose:
      'Push air down through the fin stack; the outer fan also pushes air straight out through the open back of the card.',
    quantity: '3 modeled fans',
    specifications: {
      Diameter: '100 mm',
      'Blade count': 'Illustrative',
    },
    sources: ['nitroteardown', 'nitro9070'],
    searchTerms: ['cooling', 'airflow', 'aerocurve'],
  }),
  physicalCard({
    id: 'rxfanmotor',
    name: 'Brushless fan motors',
    shortName: 'Fan motor',
    category: 'Cooling',
    parent: 'rxfan',
    description: 'A wound stator and bearing sit under each fan hub.',
    purpose:
      'Turns the fan impeller, with speed set by a control signal from the board.',
    quantity: '3 modeled motors',
    specifications: { Type: 'Brushless DC, Hall-sensed' },
    sources: ['bldc'],
    searchTerms: ['stator', 'bearing', 'motor'],
  }),
  physicalCard({
    id: 'rxheatsink',
    name: 'Heatsink fin stack',
    shortName: 'Heatsink',
    category: 'Cooling',
    parent: 'rxcard',
    description:
      'Thin aluminium fins brazed onto the heat pipes, spanning the full length of the card.',
    purpose:
      'Presents a large surface to the fan air so the heat carried by the pipes can leave the card.',
    quantity: '1 complete assembly',
    specifications: {
      Inventory: 'Fins stay together as one part',
      'Physical fin count': 'Not claimed',
    },
    sources: ['nitroteardown'],
    searchTerms: ['fins', 'radiator', 'heat sink'],
  }),
  physicalCard({
    id: 'rxheatpipe',
    name: 'Composite heat pipes',
    shortName: 'Heat pipe',
    category: 'Cooling',
    parent: 'rxcard',
    description:
      'Six sealed copper pipes run from the baseplate out into the fin stack.',
    purpose:
      'Move heat by evaporating and condensing a working fluid, far faster than solid copper could.',
    quantity: '6 heat pipes · approximate routing',
    specifications: { Count: '6', Routing: 'Approximate' },
    sources: ['nitroteardown'],
    searchTerms: ['heatpipe', 'copper'],
  }),
  physicalCard({
    id: 'rxbaseplate',
    name: 'GPU and memory baseplate',
    shortName: 'Baseplate',
    category: 'Cooling',
    parent: 'rxcard',
    description:
      'A central plate touching both the Navi 48 package and the eight memory chips around it.',
    purpose:
      'Collects heat from the processor and memory in one place and hands it to the heat pipes.',
    quantity: '1 modeled plate',
    specifications: { Contact: 'GPU and GDDR6' },
    sources: ['nitroteardown'],
    searchTerms: ['cold plate', 'contact plate'],
  }),
  physicalCard({
    id: 'rxvrmplate',
    name: 'VRM contact plates',
    shortName: 'VRM plate',
    category: 'Cooling',
    parent: 'rxcard',
    description:
      'Smaller secondary plates press on the power stages and chokes through thermal pads.',
    purpose:
      'Cool the voltage regulator, which turns a few hundred watts into heat of its own.',
    quantity: '2 modeled plates',
    specifications: { Contact: 'Power stages and chokes' },
    sources: ['nitroteardown'],
    searchTerms: ['vrm heatsink', 'secondary plate'],
  }),
  physicalCard({
    id: 'rxframe',
    name: 'Steel support frame',
    shortName: 'Frame',
    category: 'Cooling',
    parent: 'rxcard',
    description:
      'A stamped steel frame between the heatsink and the board, which Sapphire calls Frame Defense.',
    purpose:
      'Stiffens a heavy card so the board does not bend under the weight of its cooler.',
    quantity: '1 modeled frame',
    specifications: { Material: 'Steel' },
    sources: ['nitroteardown'],
    searchTerms: ['frame defense', 'stiffener', 'sag'],
  }),
  physicalCard({
    id: 'rxbackplate',
    name: 'MagniPlate backplate',
    shortName: 'Backplate',
    category: 'Cooling',
    parent: 'rxcard',
    description:
      'A removable rear cover held on by magnets, with an open vent at the far end.',
    purpose:
      'Protects the back of the board and hides the power cable, which plugs into the rear of the PCB beneath it.',
    quantity: '1 modeled plate',
    specifications: { Attachment: 'Six magnets', Removable: 'Yes' },
    sources: ['nitroteardown', 'nitro9070'],
    searchTerms: ['magniplate', 'magnetic', 'back plate'],
  }),
  physicalCard({
    id: 'rxmagnet',
    name: 'Backplate magnets',
    shortName: 'Magnet',
    category: 'Cooling',
    parent: 'rxbackplate',
    description: 'Six strong magnets seat the removable backplate cover.',
    purpose: 'Hold the cover firmly while letting it lift off without tools.',
    quantity: '6 modeled magnets',
    specifications: { Count: '6' },
    sources: ['nitroteardown'],
    searchTerms: ['magnet', 'magniplate'],
  }),
  physicalCard({
    id: 'rxlight',
    name: 'ARGB light strip',
    shortName: 'Light strip',
    category: 'Board',
    parent: 'rxcard',
    description:
      'A diffused addressable LED strip along the top edge of the shroud.',
    purpose:
      'Decorative lighting, driven from a header on the rear of the board.',
    quantity: '1 modeled strip',
    specifications: { Control: 'ARGB header on the PCB' },
    sources: ['nitroteardown'],
    searchTerms: ['rgb', 'led', 'lighting'],
  }),
  physicalCard({
    id: 'rxbracket',
    name: 'Display mounting bracket',
    shortName: 'I/O bracket',
    category: 'Board',
    parent: 'rxcard',
    description:
      'A steel bracket carrying the display outputs and the case screw tabs.',
    purpose: 'Anchors the card to the case and locates its external ports.',
    quantity: '1 modeled bracket',
    specifications: { Width: 'Three expansion slots' },
    sources: ['nitroteardown'],
    searchTerms: ['bracket', 'io'],
  }),
  physicalCard({
    id: 'rxfastener',
    name: 'Assembly fasteners',
    shortName: 'Fastener',
    category: 'Cooling',
    parent: 'rxcard',
    description: 'Screws securing the shroud, frame and cooler to the board.',
    purpose: 'Keep the cooler in firm, even contact with the processor.',
    quantity: '12 modeled fasteners',
    specifications: { 'Count and placement': 'Illustrative' },
    sources: ['nitroteardown'],
    searchTerms: ['screw', 'mounting'],
  }),
  physicalCard({
    id: 'rxthermalpad',
    name: 'Thermal pads',
    shortName: 'Thermal pad',
    category: 'Cooling',
    parent: 'rxcard',
    description:
      'Soft, thermally conductive pads between the memory and power parts and the cooler.',
    purpose:
      'Fill uneven gaps between parts of different heights so every chip touches the cooler.',
    quantity: '8 memory pads · illustrative',
    specifications: { Placement: 'Over GDDR6' },
    sources: ['nitroteardown'],
    searchTerms: ['pad', 'thermal'],
  }),
  physicalCard({
    id: 'rxtim',
    name: 'GPU thermal interface',
    shortName: 'GPU TIM',
    category: 'Cooling',
    parent: 'rxcard',
    description:
      'A thin thermal interface layer between the processor and the baseplate.',
    purpose:
      'Fills microscopic gaps between die and baseplate, lowering thermal resistance.',
    quantity: '1 modeled layer',
    specifications: { Material: 'Not asserted' },
    sources: ['nitroteardown'],
    searchTerms: ['thermal paste', 'ptm', 'tim'],
  }),
  physicalCard({
    id: 'rxretention',
    name: 'GPU retention bracket',
    shortName: 'Retention',
    category: 'Cooling',
    parent: 'rxcard',
    description:
      'A spring bracket behind the processor on the rear of the board.',
    purpose: 'Spreads cooler mounting pressure evenly across the package.',
    quantity: '1 modeled bracket',
    specifications: { Shape: 'Illustrative X bracket' },
    sources: ['nitroteardown'],
    searchTerms: ['x bracket', 'spring'],
  }),
  physicalCard({
    id: 'rxstandoff',
    name: 'Mounting standoffs',
    shortName: 'Standoff',
    category: 'Board',
    parent: 'rxcard',
    description: 'Threaded spacers around the processor.',
    purpose:
      'Set the gap between board and cooler so screws cannot bend the PCB.',
    quantity: '4 modeled standoffs',
    specifications: { Placement: 'Around the GPU package' },
    sources: ['nitroteardown'],
    searchTerms: ['spacer', 'mount'],
  }),

  // ── The board ────────────────────────────────────────────────────────────
  physicalCard({
    id: 'rxpcb',
    name: 'Printed circuit board',
    shortName: 'PCB',
    category: 'Board',
    parent: 'rxcard',
    description:
      'The board carrying the processor, memory and a sixteen-phase power supply.',
    purpose: 'Routes power and high-speed signals through its copper layers.',
    quantity: '1 illustrative board',
    specifications: {
      'Board outline': 'Illustrative, shorter than the cooler',
      'Power phases': '16 in total',
    },
    physicalAccuracy: board,
    sources: ['nitroteardown', 'packaging'],
    searchTerms: ['board', 'traces'],
  }),
  physicalCard({
    id: 'rxpackage',
    name: 'Navi 48 GPU package',
    shortName: 'Navi 48 package',
    category: 'Board',
    parent: 'rxpcb',
    open: 'navi48',
    description:
      'The substrate that carries the Navi 48 die and spreads its connections onto the board.',
    purpose:
      'Bridges the die’s microscopic bumps to board-scale power and signal traces.',
    quantity: '1 GPU package',
    specifications: {
      GPU: 'Navi 48',
      'Die area': '356.5 mm²',
      Transistors: '53.9 billion',
      Process: 'TSMC 4 nm',
    },
    physicalAccuracy: board,
    sources: ['rdna4', 'rx9070xt'],
    searchTerms: ['gpu', 'processor', 'navi'],
  }),
  physicalCard({
    id: 'rxsilicon',
    name: 'Exposed Navi 48 die',
    shortName: 'Navi 48 die',
    category: 'Compute',
    parent: 'rxpackage',
    open: 'navi48',
    description: 'A single monolithic RDNA 4 die, made on TSMC 4 nm.',
    purpose:
      'Holds every shader engine, cache and interface. Its top face hands heat to the cooler.',
    quantity: '1 die',
    specifications: {
      Design: 'Monolithic',
      Area: '356.5 mm²',
    },
    physicalAccuracy: board,
    sources: ['rdna4', 'rx9070xt'],
    searchTerms: ['silicon', 'chip', 'die'],
  }),
  physicalCard({
    id: 'rxbga',
    name: 'BGA solder connections',
    shortName: 'BGA',
    category: 'Board',
    parent: 'rxpackage',
    description: 'A grid of solder balls under the package.',
    purpose:
      'Carries power, ground and signals and mechanically fixes the package to the board.',
    quantity: 'Representative ball grid',
    specifications: { 'Ball count': 'Illustrative' },
    physicalAccuracy: board,
    sources: ['packaging'],
    searchTerms: ['solder balls', 'ball grid array'],
  }),
  physicalCard({
    id: 'rxgddr6',
    name: 'GDDR6 memory',
    shortName: 'GDDR6',
    category: 'Memory',
    parent: 'rxpcb',
    description: 'Eight 2 GB graphics memory chips around the processor.',
    purpose: 'Hold textures, geometry, frame buffers and working data.',
    quantity: '8 chips · 16 GB',
    specifications: {
      Capacity: '16 GB',
      Interface: '256-bit',
      'Data rate': '20 Gbps',
      Bandwidth: '640 GB/s',
    },
    physicalAccuracy: board,
    sources: ['rx9070xt', 'gddr6'],
    searchTerms: ['vram', 'ram', 'memory', 'framebuffer'],
  }),
  physicalCard({
    id: 'rxvrm',
    name: 'VRM chokes',
    shortName: 'Choke',
    category: 'Power',
    parent: 'rxpcb',
    description:
      'Shielded inductors, one per power phase, lined up beside the processor.',
    purpose:
      'Store energy as each phase switches and smooth it into steady current.',
    quantity: '16 chokes · 16 phases',
    specifications: {
      GPU: '10 phases',
      SoC: '3 phases',
      Memory: '2 phases',
      VDDCI: '1 phase',
    },
    physicalAccuracy: board,
    sources: ['nitroteardown', 'multiphase'],
    searchTerms: ['inductor', 'vrm', 'phases'],
  }),
  physicalCard({
    id: 'rxpowerstage',
    name: 'Integrated power stages',
    shortName: 'Power stage',
    category: 'Power',
    parent: 'rxpcb',
    description:
      'Packages that combine a gate driver and both switching transistors for one phase.',
    purpose:
      'Switch the 12 V input on and off thousands of times a second to make the low core voltages.',
    quantity: '16 modeled stages',
    specifications: { Family: 'MPS MP87993 per teardown' },
    physicalAccuracy: board,
    sources: ['nitroteardown', 'mpsphase'],
    searchTerms: ['mosfet', 'drmos', 'vrm'],
  }),
  physicalCard({
    id: 'rxpwm',
    name: 'Multiphase controllers',
    shortName: 'PWM controller',
    category: 'Power',
    parent: 'rxpcb',
    description:
      'Two digital controllers that schedule every phase of the regulators.',
    purpose:
      'Hold each voltage steady as the processor’s load jumps, by adjusting phase timing.',
    quantity: '2 modeled controllers',
    specifications: { Family: 'MPS MP2868A per teardown' },
    physicalAccuracy: board,
    sources: ['nitroteardown', 'mpscontroller'],
    searchTerms: ['pwm', 'voltage controller'],
  }),
  physicalCard({
    id: 'rxcapacitor',
    name: 'Polymer capacitors',
    shortName: 'Capacitor',
    category: 'Power',
    parent: 'rxpcb',
    description: 'Solid capacitors at the output of the power phases.',
    purpose: 'Absorb rapid current changes so the supply voltage does not sag.',
    quantity: 'Illustrative components',
    specifications: { Placement: 'Approximate' },
    physicalAccuracy: board,
    sources: ['multiphase'],
    searchTerms: ['cap', 'capacitor'],
  }),
  physicalCard({
    id: 'rxmlcc',
    name: 'Ceramic decoupling capacitors',
    shortName: 'Ceramic capacitor',
    category: 'Power',
    parent: 'rxpcb',
    description: 'Tiny ceramic capacitors close to fast-switching parts.',
    purpose: 'Suppress local supply noise.',
    quantity: 'Illustrative components',
    specifications: { 'Values and placement': 'Not asserted' },
    physicalAccuracy: board,
    sources: ['multiphase'],
    searchTerms: ['mlcc', 'decoupling'],
  }),
  physicalCard({
    id: 'rxresistor',
    name: 'Surface-mount resistors',
    shortName: 'Resistor',
    category: 'Board',
    parent: 'rxpcb',
    description:
      'Small passive parts in the board’s control and signal circuits.',
    purpose: 'Set currents, bias voltages and signal terminations.',
    quantity: 'Illustrative components',
    specifications: { 'Values and placement': 'Not asserted' },
    physicalAccuracy: board,
    sources: ['multiphase'],
    searchTerms: ['resistor', 'smd'],
  }),
  physicalCard({
    id: 'rxpcie',
    name: 'PCIe edge connector',
    shortName: 'PCIe',
    category: 'Board',
    parent: 'rxpcb',
    description: 'Gold contacts along the lower edge of the board.',
    purpose:
      'Carry commands and data between the processor and the host system.',
    quantity: '1 interface',
    specifications: { Interface: 'PCI Express 5.0 ×16' },
    physicalAccuracy: board,
    sources: ['pcie', 'rx9070xt'],
    searchTerms: ['bus', 'slot', 'connector'],
  }),
  physicalCard({
    id: 'rxpower',
    name: '12V-2x6 power socket',
    shortName: 'Power socket',
    category: 'Power',
    parent: 'rxpcb',
    description:
      'A single 16-pin socket on the rear of the board, reached through the backplate vent.',
    purpose:
      'Brings power from the supply beyond the 75 W the slot can deliver, with the cable hidden behind the motherboard tray.',
    quantity: '1 socket',
    specifications: {
      Connector: '12V-2x6',
      Location: 'Rear of PCB',
    },
    physicalAccuracy: board,
    sources: ['nitroteardown', 'psu'],
    searchTerms: ['12vhpwr', '16 pin', 'power connector'],
  }),
  physicalCard({
    id: 'rxargb',
    name: 'ARGB header',
    shortName: 'ARGB header',
    category: 'Board',
    parent: 'rxpcb',
    description: 'A small connector beside the power socket for lighting.',
    purpose: 'Links the card’s LEDs to motherboard lighting control.',
    quantity: '1 header',
    specifications: { Location: 'Rear of PCB, beside the power socket' },
    physicalAccuracy: board,
    sources: ['nitroteardown'],
    searchTerms: ['rgb header', 'lighting'],
  }),
  physicalCard({
    id: 'rxbios',
    name: 'VBIOS flash memory',
    shortName: 'VBIOS',
    category: 'Board',
    parent: 'rxpcb',
    description: 'Serial flash holding the card’s firmware.',
    purpose:
      'Stores start-up code and board settings. This card has no dual-BIOS switch.',
    quantity: '1 modeled chip',
    specifications: { 'Dual BIOS': 'No' },
    physicalAccuracy: board,
    sources: ['flash', 'nitroteardown'],
    searchTerms: ['bios', 'firmware', 'rom'],
  }),
  physicalCard({
    id: 'rxdisplayport',
    name: 'DisplayPort outputs',
    shortName: 'DisplayPort',
    category: 'Board',
    parent: 'rxpcb',
    description: 'Two shielded DisplayPort sockets on the bracket.',
    purpose: 'Connect monitors using DisplayPort 2.1a.',
    quantity: '2 DisplayPort 2.1a',
    specifications: { Standard: 'DisplayPort 2.1a' },
    physicalAccuracy: board,
    sources: ['rx9070xt', 'nitroteardown'],
    searchTerms: ['dp', 'monitor output'],
  }),
  physicalCard({
    id: 'rxhdmi',
    name: 'HDMI outputs',
    shortName: 'HDMI',
    category: 'Board',
    parent: 'rxpcb',
    description: 'Two HDMI sockets on the bracket.',
    purpose: 'Connect TVs and monitors using HDMI 2.1b.',
    quantity: '2 HDMI 2.1b',
    specifications: { Standard: 'HDMI 2.1b' },
    physicalAccuracy: board,
    sources: ['rx9070xt', 'nitroteardown'],
    searchTerms: ['hdmi', 'display output'],
  }),
  physicalCard({
    id: 'rxfanheader',
    name: 'Fan headers',
    shortName: 'Fan header',
    category: 'Board',
    parent: 'rxpcb',
    description: 'Keyed connectors for the fan wiring.',
    purpose: 'Supply fan power and read back speed.',
    quantity: '3 modeled headers',
    specifications: { Signals: 'Power, ground, tach, PWM' },
    physicalAccuracy: board,
    sources: ['mainboardmanual', 'bldc'],
    searchTerms: ['fan connector', 'pwm header'],
  }),
  physicalCard({
    id: 'rxfancable',
    name: 'Fan wiring harnesses',
    shortName: 'Fan cable',
    category: 'Cooling',
    parent: 'rxcard',
    description: 'Insulated leads from each fan motor to its header.',
    purpose:
      'Deliver power and carry the speed-control and tachometer signals.',
    quantity: '3 modeled harnesses',
    specifications: { Routing: 'Illustrative' },
    sources: ['bldc'],
    searchTerms: ['cable', 'wire'],
  }),
  physicalCard({
    id: 'rxtemperature',
    name: 'Temperature sensing ICs',
    shortName: 'Temp sensor',
    category: 'Board',
    parent: 'rxpcb',
    description: 'Small sensors near hot parts of the board.',
    purpose: 'Feed fan control and thermal protection.',
    quantity: '2 illustrative sensors',
    specifications: { Placement: 'Not asserted' },
    physicalAccuracy: board,
    sources: ['temperature'],
    searchTerms: ['thermal sensor'],
  }),
  physicalCard({
    id: 'rxesd',
    name: 'ESD protection arrays',
    shortName: 'ESD',
    category: 'Board',
    parent: 'rxpcb',
    description: 'Protection diodes next to the display connectors.',
    purpose: 'Divert static discharges away from the display circuitry.',
    quantity: '4 illustrative arrays',
    specifications: { Placement: 'Behind the outputs' },
    physicalAccuracy: board,
    sources: ['esd'],
    searchTerms: ['tvs', 'esd', 'diode'],
  }),
  physicalCard({
    id: 'rxcrystal',
    name: 'Reference clock crystal',
    shortName: 'Crystal',
    category: 'Board',
    parent: 'rxpcb',
    description: 'A quartz resonator near the processor.',
    purpose:
      'Provides the stable timing reference the GPU’s clocks derive from.',
    quantity: '1 modeled crystal',
    specifications: { Placement: 'Approximate' },
    physicalAccuracy: board,
    sources: ['crystal'],
    searchTerms: ['oscillator', 'clock', 'quartz'],
  }),

  // ── Navi 48 ──────────────────────────────────────────────────────────────
  logicalChip({
    id: 'rxgpu',
    name: 'Navi 48 architecture',
    shortName: 'Navi 48',
    category: 'Compute',
    parent: 'rxpackage',
    level: 'navi48',
    open: 'navi48',
    description:
      'A monolithic RDNA 4 processor organised as four shader engines around shared caches and interfaces.',
    purpose:
      'Runs graphics, ray tracing and machine-learning work across 64 compute units.',
    quantity: 'RX 9070 XT full configuration',
    specifications: {
      'Shader engines': '4',
      WGPs: '32',
      'Compute units': '64',
      'Stream processors': '4,096',
      'Ray accelerators': '64',
      'AI accelerators': '128',
    },
    sources: ['rdna4', 'rx9070xt'],
    searchTerms: ['chip', 'silicon', 'rdna 4', 'radeon'],
  }),
  logicalChip({
    id: 'rxse',
    name: 'Shader engine',
    shortName: 'Shader engine',
    category: 'Compute',
    parent: 'rxgpu',
    level: 'navi48',
    open: 'rxse',
    description:
      'One of four large blocks, each with its own raster pipeline and eight workgroup processors.',
    purpose:
      'Turns triangles into shaded pixels, and gives the whole chip a unit that can be switched off to build smaller products.',
    quantity: '4 on RX 9070 XT',
    specifications: {
      'WGPs per engine': '8',
      'CUs per engine': '16',
      'RX 9070 GRE': '3 engines',
      'RX 9060 XT': '2 engines',
    },
    sources: ['rdna4'],
    searchTerms: ['all shader engines', 'se'],
  }),
  logicalChip({
    id: 'rxl2',
    name: 'L2 cache',
    shortName: 'L2 cache',
    category: 'Memory',
    parent: 'rxgpu',
    level: 'navi48',
    description: 'A fast on-chip pool shared by the shader engines.',
    purpose: 'Keeps working data close to the compute units.',
    quantity: '8 MB',
    specifications: { Capacity: '8 MB' },
    sources: ['rdna4'],
    searchTerms: ['cache', 'l2 memory'],
  }),
  logicalChip({
    id: 'rxinfinity',
    name: 'Infinity Cache',
    shortName: 'Infinity Cache',
    category: 'Memory',
    parent: 'rxgpu',
    level: 'navi48',
    description:
      'Third-generation cache at the edges of the die, between the memory controllers and shader engines.',
    purpose: 'Buffers data on its way to and from external GDDR6.',
    quantity: '64 MB in 4 blocks',
    specifications: { Capacity: '64 MB', Generation: 'Third' },
    sources: ['rdna4', 'rx9070xt'],
    searchTerms: ['infinity cache', 'cache', 'l3'],
  }),
  logicalChip({
    id: 'rxmemctl',
    name: 'Memory controllers',
    shortName: 'Memory controller',
    category: 'Memory',
    parent: 'rxgpu',
    level: 'navi48',
    description: 'Four controllers driving the GDDR6 interface.',
    purpose: 'Move data between the chip and its 16 GB of external memory.',
    quantity: '4 controllers',
    specifications: {
      'Per controller': '4 × 16-bit',
      'Total interface': '256-bit',
      'Data rate': '20 Gbps',
    },
    sources: ['rdna4', 'rx9070xt'],
    searchTerms: ['memory bus', 'gddr6 interface'],
  }),
  logicalChip({
    id: 'rxcommand',
    name: 'Command processor',
    shortName: 'Command processor',
    category: 'Graphics',
    parent: 'rxgpu',
    level: 'navi48',
    description: 'The front end that receives work from the driver.',
    purpose:
      'Decodes command packets and dispatches them. RDNA 4 adds hardware packet accelerators.',
    quantity: '1 functional group',
    specifications: { Feature: 'Enhanced packet accelerators' },
    sources: ['rdna4'],
    searchTerms: ['command', 'front end', 'dispatch'],
  }),
  logicalChip({
    id: 'rxmedia',
    name: 'Media engines',
    shortName: 'Media engine',
    category: 'Graphics',
    parent: 'rxgpu',
    level: 'navi48',
    description: 'Two fixed-function video encode and decode engines.',
    purpose:
      'Compress and decompress H.264, HEVC and AV1 video without using the compute units.',
    quantity: '2 engines',
    specifications: {
      Codecs: 'H.264, HEVC, AV1 encode and decode',
      AV1: 'B-frame encoding',
    },
    sources: ['rdna4', 'rx9070xt'],
    searchTerms: ['video', 'encoder', 'decoder', 'av1'],
  }),
  logicalChip({
    id: 'rxdisplay',
    name: 'Radiance Display Engine',
    shortName: 'Display engine',
    category: 'Graphics',
    parent: 'rxgpu',
    level: 'navi48',
    description:
      'The block that scans finished frames out to the display ports.',
    purpose:
      'Handles timing, scaling and sharpening for DisplayPort 2.1a and HDMI 2.1b.',
    quantity: '1 functional group',
    specifications: {
      Outputs: 'DisplayPort 2.1a, HDMI 2.1b',
      Feature: 'Radeon Image Sharpening 2',
    },
    sources: ['rdna4', 'rdna4guide'],
    searchTerms: ['display', 'scanout', 'radiance'],
  }),
  logicalChip({
    id: 'rxhost',
    name: 'PCIe host interface',
    shortName: 'PCIe interface',
    category: 'Board',
    parent: 'rxgpu',
    level: 'navi48',
    description:
      'The on-chip endpoint for the link to the rest of the computer.',
    purpose: 'Receives commands and moves data over sixteen PCIe 5.0 lanes.',
    quantity: '1 interface',
    specifications: { Link: 'PCIe 5.0 ×16' },
    sources: ['rdna4', 'pcie'],
    searchTerms: ['pcie', 'host', 'bus'],
  }),
  logicalChip({
    id: 'rxcompress',
    name: 'Compression engines',
    shortName: 'Compression',
    category: 'Memory',
    parent: 'rxgpu',
    level: 'navi48',
    description:
      'Hardware that compresses and decompresses data as it moves through the memory hierarchy.',
    purpose:
      'Cuts the bandwidth data needs on the chip’s internal fabric, saving power.',
    quantity: '1 functional group',
    specifications: { 'Fabric bandwidth': 'About 25% lower on some workloads' },
    sources: ['rdna4'],
    searchTerms: ['compression', 'decompression', 'fabric'],
  }),
  logicalChip({
    id: 'rxmp0',
    name: 'MP0 microcontroller',
    shortName: 'MP0',
    category: 'Compute',
    parent: 'rxgpu',
    level: 'navi48',
    description:
      'A small on-chip controller for security and power management.',
    purpose:
      'Enforces access controls and privilege levels, and manages power states.',
    quantity: '1 functional group',
    specifications: { Roles: 'Security, power management' },
    sources: ['rdna4'],
    searchTerms: ['security', 'microcontroller', 'power management'],
  }),

  // ── Shader engine ────────────────────────────────────────────────────────
  logicalChip({
    id: 'rxwgp',
    name: 'Workgroup processor',
    shortName: 'WGP',
    category: 'Compute',
    parent: 'rxse',
    level: 'rxse',
    open: 'rxwgp',
    description: 'A pair of compute units that work as one scheduling group.',
    purpose:
      'Groups programmable work so it can be issued to two compute units side by side.',
    quantity: '8 per shader engine · 32 on the chip',
    specifications: { 'CUs per WGP': '2', 'WGPs per engine': '8' },
    sources: ['rdna4'],
    searchTerms: ['all wgps', 'workgroup'],
  }),
  logicalChip({
    id: 'rxraster',
    name: 'Rasterizer',
    shortName: 'Rasterizer',
    category: 'Graphics',
    parent: 'rxse',
    level: 'rxse',
    description: 'Works out which pixels each projected triangle covers.',
    purpose: 'Connects geometry to pixel coverage on screen.',
    quantity: '1 per shader engine',
    specifications: { Scope: 'Shader engine' },
    sources: ['rdna4'],
    searchTerms: ['raster', 'coverage'],
  }),
  logicalChip({
    id: 'rxprim',
    name: 'Primitive unit',
    shortName: 'Prim unit',
    category: 'Graphics',
    parent: 'rxse',
    level: 'rxse',
    description:
      'Fixed-function hardware that prepares triangles for rasterizing.',
    purpose: 'Sets up primitives after vertex processing.',
    quantity: '1 per shader engine',
    specifications: { Scope: 'Shader engine' },
    sources: ['rdna4'],
    searchTerms: ['primitive', 'triangle setup', 'geometry'],
  }),
  logicalChip({
    id: 'rxrb',
    name: 'Render backends',
    shortName: 'RB+',
    category: 'Graphics',
    parent: 'rxse',
    level: 'rxse',
    description: 'The final pixel-processing stages of the pipeline.',
    purpose: 'Carry out raster operations such as blending and depth testing.',
    quantity: '2 per shader engine',
    specifications: { 'ROPs on RX 9070 XT': '128' },
    sources: ['rdna4', 'rx9070xt'],
    searchTerms: ['rops', 'pixel', 'blending', 'render backend'],
  }),
  logicalChip({
    id: 'rxra',
    name: 'Render assist units',
    shortName: 'RA',
    category: 'Graphics',
    parent: 'rxse',
    level: 'rxse',
    description: 'Helper blocks drawn beside the render backends.',
    purpose: 'Support the render backends in the pixel stage.',
    quantity: '4 per shader engine',
    specifications: { Scope: 'Shader engine' },
    physicalAccuracy:
      'AMD labels these blocks RA in its Navi 48 diagram without detailing their function; the description is limited accordingly.',
    sources: ['rdna4'],
    searchTerms: ['render assist'],
  }),

  // ── Workgroup processor ──────────────────────────────────────────────────
  logicalChip({
    id: 'rxcu',
    name: 'Compute unit',
    shortName: 'CU',
    category: 'Compute',
    parent: 'rxwgp',
    level: 'rxwgp',
    open: 'rxcu',
    description:
      'RDNA 4’s unified execution unit: vector arithmetic, matrix math and ray tracing in one block.',
    purpose:
      'Runs shader and compute threads, with its own caches and registers close at hand.',
    quantity: '2 per WGP · 64 on the chip',
    specifications: {
      'Stream processors': '64 per CU',
      'Ray accelerators': '1 per CU',
      'AI accelerators': '2 per CU',
      'Aggregate CU cache': '2 MB, as AMD states it',
    },
    sources: ['rdna4', 'rx9070xt'],
    searchTerms: ['all compute units', 'cu', 'stream processor'],
  }),
  logicalChip({
    id: 'rxslm',
    name: 'Shared memory',
    shortName: 'Shared memory',
    category: 'Memory',
    parent: 'rxwgp',
    level: 'rxwgp',
    description: 'Local memory the threads in a workgroup can all reach.',
    purpose: 'Lets cooperating threads exchange intermediate results quickly.',
    quantity: '128 KB',
    specifications: { Capacity: '128 KB' },
    physicalAccuracy: interpretive,
    sources: ['rdna4'],
    searchTerms: ['slm', 'shared local memory', 'l1'],
  }),
  logicalChip({
    id: 'rxsched',
    name: 'Scheduler units',
    shortName: 'Scheduler',
    category: 'Compute',
    parent: 'rxwgp',
    level: 'rxwgp',
    description: 'Hardware that chooses which ready threads run next.',
    purpose: 'Keep both compute units supplied with work.',
    quantity: 'Functional group',
    specifications: { View: 'Functional group' },
    physicalAccuracy: interpretive,
    sources: ['rdna4'],
    searchTerms: ['dispatch', 'scheduling'],
  }),
];

// ── Compute unit ─────────────────────────────────────────────────────────────
// Blocks read from AMD's compute engine diagram. Written as a table because
// each row has the same shape, the way the RTX 5090 board families are.
const cuParts: [
  id: string,
  name: string,
  shortName: string,
  category: Category,
  description: string,
  purpose: string,
  quantity: string,
  specifications: Record<string, string>,
  searchTerms: string[],
][] = [
  [
    'rxalu',
    'FMA arithmetic logic unit',
    'ALU · FMA',
    'Compute',
    'A 32-wide SIMD unit for floating-point multiply and accumulate.',
    'Performs the vector floating-point arithmetic behind shaders and compute kernels.',
    '1 per CU',
    { Width: '32-wide SIMD', Operations: 'Floating point' },
    ['alu', 'simd', 'fp32', 'vector'],
  ],
  [
    'rxaluint',
    'FMA/INT arithmetic logic unit',
    'ALU · FMA/INT',
    'Compute',
    'A second 32-wide SIMD unit that handles integer as well as floating-point work.',
    'Adds integer arithmetic alongside the floating-point unit.',
    '1 per CU',
    { Width: '32-wide SIMD', Operations: 'Floating point and integer' },
    ['alu', 'simd', 'integer'],
  ],
  [
    'rxmatrix',
    'Matrix accelerators',
    'Matrix accelerator',
    'Compute',
    'Hardware for dense and sparse matrix multiply-accumulate.',
    'Speeds up the neural networks behind upscaling, denoising and AI workloads.',
    '2 per CU · 128 on the chip',
    {
      Generation: 'Third',
      'Tensor inputs': '16, 8 and 4 bit',
      Sparsity: '4:2 structured',
    },
    ['ai accelerator', 'ml', 'fp8', 'matrix', 'tensor'],
  ],
  [
    'rxtlu',
    'Transcendental logic units',
    'TLU',
    'Compute',
    'An 8-wide unit for functions beyond basic arithmetic.',
    'Evaluates operations such as trigonometric and exponential functions.',
    '8-wide per CU',
    { Width: '8-wide' },
    ['transcendental', 'math'],
  ],
  [
    'rxray',
    'Ray accelerator',
    'Ray accelerator',
    'Graphics',
    'Dedicated ray traversal and intersection hardware.',
    'Finds where rays meet scene geometry, using wider BVH trees and oriented bounding boxes.',
    '1 per CU · 64 on the chip',
    {
      Generation: 'Third',
      Intersectors: '8 ray/box, 2 ray/triangle',
      BVH: '8-wide',
    },
    ['ray tracing', 'bvh', 'rt'],
  ],
  [
    'rxl0',
    'Ray accelerator L0 cache',
    'RA L0 cache',
    'Memory',
    'A small cache right beside the ray accelerator.',
    'Keeps the BVH nodes being traversed within immediate reach.',
    '32 KB',
    { Capacity: '32 KB' },
    ['l0', 'bvh cache'],
  ],
  [
    'rxvgpr',
    'Vector general-purpose registers',
    'Vector GPR',
    'Memory',
    'Register storage for the vector units.',
    'Holds the values running threads are working on. RDNA 4 allocates it dynamically.',
    '192 KB',
    { Capacity: '192 KB', Allocation: 'Dynamic' },
    ['registers', 'gpr'],
  ],
  [
    'rxsgpr',
    'Scalar general-purpose registers',
    'Scalar GPR',
    'Memory',
    'Register storage for the scalar unit.',
    'Holds scalar values beside the scalar unit.',
    '8 KB',
    { Capacity: '8 KB' },
    ['registers', 'scalar'],
  ],
  [
    'rxscalar',
    'Scalar unit',
    'Scalar unit',
    'Compute',
    'A unit for scalar operations, now with floating-point support.',
    'Handles work that does not benefit from vector width.',
    '1 per CU',
    { Feature: 'Floating point support' },
    ['scalar'],
  ],
  [
    'rxscache',
    'Scalar cache',
    'Scalar cache',
    'Memory',
    'A cache attached to the scalar unit.',
    'Keeps scalar data close to where it is used.',
    '16 KB',
    { Capacity: '16 KB' },
    ['scalar cache'],
  ],
  [
    'rxsic',
    'Shader instruction cache',
    'Instruction cache',
    'Memory',
    'Storage for the shader instructions being executed.',
    'Avoids fetching the same instructions repeatedly.',
    '32 KB',
    { Capacity: '32 KB' },
    ['instruction cache', 'shader cache'],
  ],
  [
    'rxtexls',
    'Texture load/store units',
    'Texture load/store',
    'Graphics',
    'The path that reads texture data and writes results.',
    'Brings sampled surface data into the compute unit and stores outputs.',
    'Functional group',
    { View: 'Functional group' },
    ['texture', 'load store', 'sampling'],
  ],
];
for (const [
  id,
  name,
  shortName,
  category,
  description,
  purpose,
  quantity,
  specifications,
  searchTerms,
] of cuParts)
  radeonConcepts.push(
    logicalChip({
      id,
      name,
      shortName,
      category,
      parent: 'rxcu',
      level: 'rxcu',
      description,
      purpose,
      quantity,
      specifications,
      physicalAccuracy: `${architecture} ${interpretive}`,
      sources: ['rxmatrix', 'rxray'].includes(id)
        ? ['rdna4', 'rx9070xt']
        : ['rdna4'],
      searchTerms,
    }),
  );
