import { concept, standard, type Concept } from '../concept.ts';

const internals =
  'Representative 2.5-inch SATA SSD construction. Package count, controller choice and PCB outline vary by product.';

export const ssdConcepts: Concept[] = [
  concept({
    id: 'ssdcase',
    name: 'SSD base tray',
    shortName: 'Base tray',
    category: 'Storage',
    parent: 'ssd',
    level: 'ssd',
    description:
      'The folded lower half of the 2.5-inch enclosure, with side mounting points.',
    purpose:
      'Protects the electronics and gives a small board the standard drive-bay footprint.',
    quantity: '1 modeled tray',
    specifications: { Format: '2.5-inch · 7 mm' },
    representationType: 'physical',
    physicalAccuracy: standard,
    sources: ['samsungsata'],
    searchTerms: ['case', 'shell', 'enclosure', 'tray'],
  }),
  concept({
    id: 'ssdcover',
    name: 'SSD cover',
    shortName: 'Cover',
    category: 'Storage',
    parent: 'ssd',
    level: 'ssd',
    description: 'A thin stamped lid screwed to the base tray.',
    purpose:
      'Closes the enclosure while remaining removable for manufacture and inspection.',
    quantity: '1 modeled cover',
    specifications: { Material: 'Stamped metal' },
    representationType: 'physical',
    physicalAccuracy: internals,
    sources: ['samsungsata'],
    searchTerms: ['lid', 'top', 'shell'],
  }),
  concept({
    id: 'ssdboard',
    name: 'SSD controller board',
    shortName: 'SSD PCB',
    category: 'Board',
    parent: 'ssd',
    level: 'ssd',
    description:
      'A compact printed circuit board carrying the flash, controller and interface electronics.',
    purpose:
      'Routes power and high-speed signals between the SATA connector and every storage package.',
    quantity: '1 modeled board',
    specifications: { Interface: 'SATA 6 Gb/s' },
    representationType: 'physical',
    physicalAccuracy: internals,
    sources: ['samsungsata', 'ssdarchitecture'],
    searchTerms: ['pcb', 'board', 'circuit'],
  }),
  concept({
    id: 'ssdcontroller',
    name: 'Flash controller',
    shortName: 'Controller',
    category: 'Compute',
    parent: 'ssdboard',
    level: 'ssd',
    description:
      'The processor that presents a SATA drive while managing a much larger array of NAND cells behind it.',
    purpose:
      'Maps logical blocks, corrects errors, spreads wear and moves data between the host and flash channels.',
    quantity: '1 modeled controller',
    specifications: { Roles: 'FTL · ECC · wear levelling' },
    representationType: 'physical',
    physicalAccuracy: internals,
    sources: ['ssdarchitecture', 'samsungsata'],
    searchTerms: ['flash translation layer', 'ecc', 'wear leveling'],
  }),
  concept({
    id: 'ssdnand',
    name: 'NAND flash packages',
    shortName: 'NAND flash',
    category: 'Storage',
    parent: 'ssdboard',
    level: 'ssd',
    description:
      'Non-volatile memory packages containing stacked arrays of charge-trapping cells.',
    purpose:
      'Retains data with the power off; several packages let the controller access flash channels in parallel.',
    quantity: '4 illustrative packages',
    specifications: { Storage: 'Non-volatile NAND flash' },
    representationType: 'physical',
    physicalAccuracy: internals,
    sources: ['samsungsata', 'ssdarchitecture'],
    searchTerms: ['flash', 'memory', 'chips', 'storage cells'],
  }),
  concept({
    id: 'ssddram',
    name: 'SSD DRAM cache',
    shortName: 'DRAM cache',
    category: 'Memory',
    parent: 'ssdboard',
    level: 'ssd',
    description: 'A small volatile memory package beside the controller.',
    purpose:
      'Keeps frequently used mapping and write data close to the controller; some SSD designs omit it.',
    quantity: '1 modeled package',
    specifications: { Role: 'Mapping and write cache' },
    representationType: 'physical',
    physicalAccuracy: internals,
    sources: ['samsungsata', 'ssdarchitecture'],
    searchTerms: ['cache', 'dram', 'buffer'],
  }),
  concept({
    id: 'ssddata',
    name: 'SATA data connector',
    shortName: 'SATA data',
    category: 'Storage',
    parent: 'ssdboard',
    level: 'ssd',
    description:
      'The narrow L-keyed connector carrying the serial link to the motherboard.',
    purpose: 'Carries commands and data; it does not power the drive.',
    quantity: '1 modeled connector',
    specifications: { Contacts: '7-pin', Link: 'SATA 6 Gb/s' },
    representationType: 'physical',
    physicalAccuracy: standard,
    sources: ['sata', 'samsungsata'],
    searchTerms: ['sata', 'data cable', '7 pin'],
  }),
  concept({
    id: 'ssdpower',
    name: 'SATA power connector',
    shortName: 'SATA power',
    category: 'Power',
    parent: 'ssdboard',
    level: 'ssd',
    description: 'The wide L-keyed connector supplied by the power supply.',
    purpose:
      'Feeds the drive’s power rails; a data cable alone cannot make the SSD operate.',
    quantity: '1 modeled connector',
    specifications: { Contacts: '15-pin', Rails: '3.3 V · 5 V · 12 V defined' },
    representationType: 'physical',
    physicalAccuracy: standard,
    sources: ['sata', 'psu'],
    searchTerms: ['sata', 'power cable', '15 pin'],
  }),
];
